from __future__ import annotations

import re

from modori.steps.regression import REGRESSION_ENGINE_VOCABULARY
from modori.steps.statistics import STATISTICS_ENGINE_VOCABULARY


USER_FACING_EXCLUDED_KEYS = frozenset(
    {
        "classical",
        "classical_f",
        "after",
        "before",
        "dv",
        "effect",
        "effect_value",
        "group",
        "group_1",
        "group_2",
        "hc3",
        "item",
        "model_test",
        "predictor",
        "regression_v1",
        "reliability_v1",
        "report_apa_v1",
        "robust_wald_f",
        "stats_compare_groups",
        "stats_regression_ols",
        "stats_reliability",
        "test",
        "ttest_v1",
        "mwu_v1",
    }
)


_HELP_KEY_ALIASES: dict[str, str] = {
    "95_ci": "confidence_interval",
    "adj_r_squared": "adjusted_r_squared",
    "alpha": "cronbach_alpha",
    "beta": "standardized_beta",
    "bp_p": "breusch_pagan",
    "breusch_pagan_p": "breusch_pagan",
    "ci95": "confidence_interval",
    "cook_threshold": "cooks_distance",
    "cronbach_s_alpha": "cronbach_alpha",
    "cronbachs_alpha": "cronbach_alpha",
    "df_model": "df",
    "df_resid": "df",
    "dw": "durbin_watson",
    "item_total_corr": "corrected_item_total_correlation",
    "levene_p": "levene",
    "max_cooks": "cooks_distance",
    "max_vif": "vif",
    "mean_diff_ci": "confidence_interval",
    "n_dropped": "listwise_deletion",
    "n_obs": "listwise_deletion",
    "n_total": "listwise_deletion",
    "p": "p_value",
    "shapiro_diff_p": "shapiro_wilk",
    "se": "se",
    "shapiro_g1_p": "shapiro_wilk",
    "shapiro_g2_p": "shapiro_wilk",
    "shapiro_p": "shapiro_wilk",
    "shapiro_resid_p": "shapiro_wilk",
    "vif": "vif",
}


HELP_KEYS: dict[str, str] = {
    "analysis.descriptives_table1": "descriptives-table1",
    "analysis.frequency_crosstab": "frequency-crosstab",
    "analysis.correlation": "correlation-analysis",
    "analysis.anova_oneway": "anova-oneway",
    "analysis.kruskal_wallis": "kruskal-wallis-test",
    "analysis.ancova": "ancova",
    "analysis.factor_pca": "factor-pca",
    "analysis.repeated_measures_anova": "repeated-measures-anova",
    "analysis.friedman": "friedman-test",
    "analysis.mediation": "mediation-analysis",
    "analysis.moderated_mediation": "moderated-mediation",
    "analysis_descriptives_table1": "descriptives-table1",
    "analysis_factor_pca": "factor-pca",
    "descriptives_table1": "descriptives-table1",
    "frequency_crosstab": "frequency-crosstab",
    "correlation": "correlation-analysis",
    "anova_oneway": "anova-oneway",
    "one_way_anova": "anova-oneway",
    "kruskal_wallis": "kruskal-wallis-test",
    "ancova": "ancova",
    "factor_pca": "factor-pca",
    "repeated_measures_anova": "repeated-measures-anova",
    "friedman": "friedman-test",
    "mediation": "mediation-analysis",
    "moderated_mediation": "moderated-mediation",
    "pca": "principal-component-analysis",
    "principal_component_analysis": "principal-component-analysis",
    "efa": "exploratory-factor-analysis",
    "exploratory_factor_analysis": "exploratory-factor-analysis",
    "kmo": "kmo",
    "bartlett_sphericity": "bartlett-sphericity",
    "parallel_analysis": "parallel-analysis",
    "factor_loading": "factor-loading",
    "communality": "communality",
    "uniqueness": "uniqueness",
    "chi_square": "chi-square-test",
    "pearson_chi_square": "chi-square-test",
    "fisher_exact": "fisher-exact-test",
    "cramers_v": "cramers-v",
    "pearson_correlation": "pearson-correlation",
    "spearman_correlation": "spearman-correlation",
    "pairwise_deletion": "pairwise-deletion",
    "tukey_hsd": "tukey-hsd",
    "games_howell": "games-howell",
    "eta_squared": "eta-squared",
    "omega_squared": "omega-squared",
    "epsilon_squared": "epsilon-squared",
    "mean_rank": "mean-rank",
    "homogeneity_of_regression_slopes": "homogeneity-of-regression-slopes",
    "mauchly_sphericity": "mauchly-sphericity",
    "greenhouse_geisser": "greenhouse-geisser",
    "huynh_feldt": "huynh-feldt",
    "adjusted_mean": "adjusted-mean",
    "partial_eta_squared": "partial-eta-squared",
    "friedman_test": "friedman-test",
    "kendalls_w": "kendalls-w",
    "indirect_effect": "indirect-effect",
    "bootstrap_ci": "bootstrap-ci",
    "conditional_indirect_effect": "conditional-indirect-effect",
    "index_of_moderated_mediation": "index-of-moderated-mediation",
    "alpha": "cronbach-alpha",
    "cronbach-alpha": "cronbach-alpha",
    "cronbach_alpha": "cronbach-alpha",
    "cronbachs_alpha": "cronbach-alpha",
    "student_t": "student-t-test",
    "welch": "welch-t-test",
    "welch-t-test": "welch-t-test",
    "welch_t": "welch-t-test",
    "mann_whitney": "mann-whitney-u",
    "paired_t": "paired-samples-t-test",
    "wilcoxon": "wilcoxon-signed-rank",
    "cohen_d": "cohens-d",
    "cohen_dz": "cohens-dz",
    "rank_biserial": "rank-biserial",
    "mcdonald_omega": "mcdonald-omega",
    "corrected_item_total_correlation": "corrected-item-total-correlation",
    "p_value": "p-value",
    "confidence_interval": "confidence-interval",
    "standardized_beta": "standardized-beta",
    "r_squared": "r-squared",
    "adjusted_r_squared": "adjusted-r-squared",
    "f_statistic": "f-test",
    "vif": "vif",
    "breusch_pagan": "breusch-pagan",
    "durbin_watson": "durbin-watson",
    "shapiro_wilk": "shapiro-wilk",
    "cooks_distance": "cooks-distance",
    "levene": "levene-test",
    "normality": "normality",
    "homoscedasticity": "homoscedasticity",
    "homogeneity_of_variance": "homogeneity-of-variance",
    "independence_of_errors": "independence-of-errors",
    "multicollinearity": "multicollinearity",
    "linearity": "linearity",
    "listwise_deletion": "listwise-deletion",
    "statistical_significance": "statistical-significance",
    "b": "unstandardized-coefficient",
    "se": "standard-error",
    "t": "test-statistic",
    "statistic": "test-statistic",
    "df": "degrees-of-freedom",
    "alpha_if_deleted": "alpha-if-deleted",
}


ENGINE_VOCABULARY: set[str] = set(STATISTICS_ENGINE_VOCABULARY) | set(
    REGRESSION_ENGINE_VOCABULARY
)


def normalize_help_key(entity_key: str) -> str | None:
    raw = str(entity_key).strip()
    if not raw:
        return None
    snake = re.sub(r"[^A-Za-z0-9]+", "_", raw).strip("_").lower()
    if not snake:
        return None
    return _HELP_KEY_ALIASES.get(snake, snake)
