from __future__ import annotations

from typing import Protocol


class AnalysisPipelineOps(Protocol):
    def step_collection(self) -> object | None: ...

    def known_variable_keys(self) -> set[str] | None: ...

    def current_dataset(self) -> object | None: ...

    def edit_params(self, step_id: str, params: dict[str, object]) -> None: ...


class MetadataPipelineOps(Protocol):
    def has_pipeline(self) -> bool: ...

    def has_variable(self, variable_key: str) -> bool: ...

    def has_step(self, step_id: str) -> bool: ...

    def edit_params(self, step_id: str, params: dict[str, object]) -> None: ...

    def insert_metadata_step(self, variable_key: str, step: object) -> None: ...


class DataTransformPipelineOps(Protocol):
    def has_pipeline(self) -> bool: ...

    def has_variable(self, variable_key: str) -> bool: ...

    def any_output_exists(
        self,
        output_keys: list[str],
        *,
        exclude_step_id: str | None = None,
    ) -> bool: ...

    def insert_or_replace_transform_step(self, step: object) -> None: ...


class DataSessionPipelineOps(Protocol):
    def has_downstream_steps(self) -> bool: ...


class PipelineStateOps(Protocol):
    def steps(self, fallback: list[object] | None = None) -> list[object]: ...

    def step_chain_text(self, steps: list[object] | None = None) -> str: ...
