from __future__ import annotations


UI_STRINGS_EN = {
    "app.title": "Modori",
    "boundary.reconfirmation_required": "The data structure changed. Review the candidate configuration again or apply an analysis method manually.",
    "dialog.import.cancel": "Cancel",
    "dialog.import.columns_count": "Selected columns",
    "dialog.import.columns_count_separator": ": ",
    "dialog.import.columns_count_total_separator": " / ",
    "dialog.import.columns_empty": "Select at least one column to import.",
    "dialog.import.columns_reset": "Include all columns",
    "dialog.import.columns_search": "Search columns",
    "dialog.import.columns_title": "Columns to import",
    "dialog.import.confirm": "Import",
    "dialog.import.data_start_row": "First data row",
    "dialog.import.drop_aggregate_rows": "Exclude aggregate and total rows",
    "dialog.import.drop_duplicate_rows": "Exclude fully duplicated rows",
    "dialog.import.header_row": "Header row",
    "dialog.import.header_rows": "Header row count",
    "dialog.import.preserve_metadata": "Keep value labels and missing-value codes",
    "dialog.import.preserve_metadata_detail": "Preserve value labels and missing-value codes from supported files.",
    "dialog.import.preview_accessible": "Data preview",
    "dialog.import.refresh_preview": "Refresh preview",
    "dialog.import.review_accessible": "Review import row classification",
    "dialog.import.review_title": "Review row classification",
    "dialog.import.sheet_recovery": (
        "No table was found on the default sheet. Select the sheet that contains "
        "the table and refresh the preview."
    ),
    "dialog.import.sheet_name": "Sheet",
    "dialog.import.settings": "Import settings",
    "dialog.import.settings_collapse": "Collapse settings",
    "dialog.import.title": "Import data",
    "dialog.report.description": "Export the current analysis results to Word (.docx).",
    "dialog.report.conflict_body": "Replacing it removes the previous contents.",
    "dialog.report.conflict_title": "A report with this name already exists",
    "dialog.report.export_word": "Save to Word",
    "dialog.report.include_association": "Include frequencies and correlations",
    "dialog.report.include_comparison": "Include group comparisons",
    "dialog.report.include_figures": "Include figures",
    "dialog.report.include_descriptives": "Include descriptives",
    "dialog.report.include_dimension_reduction": "Include factor analysis and PCA",
    "dialog.report.include_group_models": "Include ANOVA and ANCOVA",
    "dialog.report.include_regression": "Include regression",
    "dialog.report.include_reliability": "Include reliability",
    "dialog.report.language": "Report language",
    "dialog.report.language.en": "English",
    "dialog.report.language.ko": "Korean",
    "dialog.report.keep_existing": "Keep existing file",
    "dialog.report.replace_existing": "Replace existing file",
    "dialog.report.sections": "Content to include",
    "dialog.report.title": "Export report",
    "data.grid_accessible": "Data table",
    "data.grid_columns": "columns",
    "data.grid_empty": "No data to display.",
    "data.grid_extent_separator": " · ",
    "data.grid_keyboard_help": (
        "Use the arrow keys to move. Ctrl+Shift+F fits the current column; "
        "Ctrl+Shift+R resets all column widths."
    ),
    "data.grid_rows": "rows",
    "data.edit_policy": "Direct cell editing will be enabled after a reproducible editing step is available.",
    "entry.guided": "GUIDED MODE",
    "entry.guided_description": (
        "Follow guided steps from your research question and data structure to a "
        "reviewable analysis candidate.\n"
        "Experimental research guide · You review the setup and start the run"
    ),
    "entry.heading": "Get started",
    "entry.language": "Language",
    "entry.promise": "A clear choice for statistical work.\nWelcome to Modori.",
    "entry.selected": "Selected",
    "entry.standard": "PRO MODE",
    "entry.standard_description": "Choose the analysis method and variable roles yourself.",
    "entry.open_data": "Open data file",
    "entry.footer": "Free · Open source · Local",
    "entry.recent": "Recent files",
    "explain.close": "Close",
    "explain.close_accessible": "Close explanation",
    "explain.title": "Explanation",
    "guide.ancova": "Covariate-adjusted group comparison",
    "guide.anova_oneway": "Mean differences across three or more groups",
    "guide.comparison": "Mean difference between two groups",
    "guide.correlation": "Correlation",
    "guide.covariates_accessible": "Covariates",
    "guide.covariates_placeholder": "Covariates: age, pretest",
    "guide.confirm_review": "I checked the research question, variable roles, and sample structure.",
    "guide.default_recommendation": "Current review candidate",
    "guide.descriptives": "Descriptive statistics table",
    "guide.frequency_crosstab": "Frequencies and crosstabs",
    "guide.factor_pca": "Factor analysis / PCA",
    "guide.group_accessible": "Group variable",
    "guide.group_placeholder": "Group variable",
    "guide.dependent_placeholder": "Dependent variable",
    "guide.items_accessible": "Reliability item variables",
    "guide.items_placeholder": "Item variables: q1, q2, q3",
    "guide.experimental_status": "Experimental guide",
    "guide.form_unavailable": "This candidate cannot yet be configured in the guided view. Choose a supported analysis from manual selection.",
    "guide.manual_selection": "Manual selection",
    "guide.no_recommendation": "No analysis candidate to review",
    "guide.other_recommendations": "Other candidates",
    "guide.outcome_accessible": "Outcome variable",
    "guide.outcome_placeholder": "Outcome variable",
    "guide.predictors_accessible": "Predictor variables",
    "guide.predictors_placeholder": "Predictors: x1, x2",
    "guide.prepare_review": "Review configuration",
    "guide.reason": "Reason",
    "guide.regression": "Predict with multiple variables",
    "guide.reliability": "Scale reliability",
    "guide.kruskal_wallis": "Rank-based comparison of three or more groups",
    "guide.run_manual": "Run selected analysis",
    "guide.run_reviewed": "Run after review",
    "guide.review_required": "Review the variables and configuration, then confirm before running.",
    "guide.review_state": "Review status",
    "guide.title": "Analysis candidate guidance",
    "guide.variables_accessible": "Analysis variables",
    "guide.variables_placeholder": "Variables: q1, q2, q3",
    "language.en": "English",
    "language.ko": "한국어",
    "loading.calculating": "Loading",
    "pipeline.apply_ancova": "Apply ANCOVA",
    "pipeline.apply_anova_oneway": "Apply ANOVA",
    "pipeline.apply_comparison": "Apply comparison",
    "pipeline.apply_correlation": "Apply correlation",
    "pipeline.apply_descriptives": "Apply descriptives",
    "pipeline.apply_frequency_crosstab": "Apply frequencies",
    "pipeline.apply_factor_pca": "Apply factor analysis / PCA",
    "pipeline.apply_kruskal_wallis": "Apply K-W",
    "pipeline.apply_regression": "Apply regression",
    "pipeline.apply_reliability": "Apply reliability",
    "pipeline.analysis_type": "Analysis method",
    "pipeline.covariates_accessible": "Covariates",
    "pipeline.covariates_placeholder": "Covariates",
    "pipeline.dependent_accessible": "Standard regression dependent variable",
    "pipeline.dependent_placeholder": "Dependent",
    "pipeline.group_accessible": "Standard group variable",
    "pipeline.group_placeholder": "Group",
    "pipeline.items_accessible": "Standard reliability items",
    "pipeline.items_placeholder": "q1, q2, q3",
    "pipeline.outcome_accessible": "Standard outcome variable",
    "pipeline.outcome_placeholder": "Outcome",
    "pipeline.predictors_accessible": "Standard regression predictors",
    "pipeline.predictors_placeholder": "x1, x2",
    "pipeline.run": "Run",
    "pipeline.rerun": "Run again",
    "pipeline.variables_accessible": "Analysis variables",
    "pipeline.variables_placeholder": "Variables",
    "privacy.local": "Your data never leaves this computer",
    "results.error_prefix": "Error: ",
    "results.empty": "Waiting",
    "results.empty_message": "Results will appear here after you run an analysis.",
    "results.figure": "Figure",
    "results.latest": "Latest",
    "results.notes": "Notes",
    "results.path": "File location",
    "results.report_preview": "Result summary",
    "results.running": "Calculating",
    "results.stale": "Previous result",
    "results.table": "Result table",
    "results.title": "Results",
    "results.detail_title": "Result table",
    "results.view_wide": "Open wide table",
    "results.why_this_test": "Why this analysis was selected",
    "settings.close": "Close",
    "settings.description": "Choose display options and how recent items are stored.",
    "settings.explain": "Explanations",
    "settings.explain_detail": "Show why an analysis was selected and explain statistical terms.",
    "settings.recent_files": "Save recent items",
    "settings.recent_files_detail": "Turning this off also removes recent items stored on this computer.",
    "settings.reduce_effects": "Reduce visual effects",
    "settings.reduce_effects_detail": "Reduce sheen and motion while preserving the information structure.",
    "settings.title": "Settings",
    "splash.subtitle": "Preparing the statistics engine",
    "transform.apply_reverse": "Create reverse-coded variable",
    "transform.apply_scale": "Create scale-score variable",
    "transform.map_apply": "Add value-cleaning step",
    "transform.map_column": "Variable",
    "transform.map_missing": "Values to mark missing",
    "transform.map_missing_placeholder": "Example: no response, unknown",
    "transform.map_new_value": "New value",
    "transform.map_preview_missing": "rows marked missing",
    "transform.map_preview_to": "rows → ",
    "transform.map_rules": "Edit rules",
    "transform.map_rules_placeholder": "Example: M ale=Male",
    "transform.map_summary_rows": "rows will be edited",
    "transform.map_summary_rows_with_text": "rows will be edited + free-text rules",
    "transform.map_summary_text": "Free-text rules will be applied",
    "transform.map_suffix": "New-variable suffix",
    "transform.map_suffix_default": "_edited",
    "transform.map_title": "Edit values",
    "transform.map_to_missing": "Missing",
    "transform.map_values": "Current values",
    "transform.method_mean": "Mean",
    "transform.method_sum": "Sum",
    "transform.min_valid": "Valid-response ratio",
    "transform.policy_conservative": "Complete responses only",
    "transform.policy_custom": "Custom",
    "transform.policy_survey": "Survey default",
    "transform.reverse_columns": "Variables to reverse-code",
    "transform.reverse_columns_placeholder": "Example: q3, q7",
    "transform.reverse_suffix": "New-variable suffix",
    "transform.reverse_suffix_placeholder": "_R",
    "transform.reverse_title": "Reverse coding",
    "transform.scale_items": "Item variables",
    "transform.scale_items_placeholder": "Example: q1, q2, q3",
    "transform.scale_max": "Maximum",
    "transform.scale_method": "Calculation method",
    "transform.scale_min": "Minimum",
    "transform.scale_name": "New variable name",
    "transform.scale_name_placeholder": "Example: job_sat",
    "transform.scale_policy": "Missing-value handling",
    "transform.scale_title": "Create scale score",
    "transform.source_protected": "Source data is not edited directly. Transformations are recorded as new steps and variables.",
    "transform.unify_apply": "Add label-unification step",
    "transform.unify_title": "Suggested label unification",
    "variable.key_accessible": "Variable key",
    "variable.key_placeholder": "Variable key",
    "variable.label_placeholder": "Variable label",
    "variable.measure_accessible": "Measure level",
    "variable.measure_edit": "Change measure level",
    "variable.measure_nominal": "Nominal",
    "variable.measure_ordinal": "Ordinal",
    "variable.measure_scale": "Scale",
    "variable.metadata_apply": "Update properties",
    "variable.missing_codes_placeholder": "Missing codes: 9, 99",
    "work.analysis": "Run analysis again",
    "work.analysis_run": "Run analysis",
    "work.reconfirmation_required": "Configuration review required",
    "work.data": "Open data",
    "work.data_menu": "Data menu",
    "work.data_sheet_window": "Open data sheet",
    "work.data_view": "Data",
    "work.guided": "GUIDED MODE",
    "work.report": "Report",
    "work.report_menu": "Report menu",
    "work.standard": "PRO MODE",
    "work.transform_view": "Transform",
    "work.variable_view": "Variables",
    "guide.anova_factorial": "Mean differences and interaction across two factors",
    "guide.candidate_label": "Analysis candidate",
    "guide.candidate_list": "Analysis candidate list",
    "guide.confirm_candidate": "I reviewed the research question, variable roles, and sample structure.",
    "guide.explanation_unavailable": "The supporting explanation is unavailable.",
    "guide.factorial_factor_a": "Factor A",
    "guide.factorial_factor_b": "Factor B",
    "guide.factorial_levels_a": "Factor A levels",
    "guide.factorial_levels_b": "Factor B levels",
    "guide.factorial_outcome": "Outcome variable",
    "guide.friedman": "Repeated-measures rank analysis",
    "guide.logistic_event": "Outcome value treated as the event",
    "guide.logistic_event_accessible": "Logistic-regression event value",
    "guide.logistic_reference": "Reference category",
    "guide.logistic_reference_accessible": "Logistic-regression reference category",
    "guide.logistic_regression": "Factors associated with one of two outcomes",
    "guide.measures_accessible": "Repeated-measure variables",
    "guide.measures_placeholder": "Repeated measures: time1, time2, time3",
    "guide.mediation": "Mediation analysis",
    "guide.mediator_accessible": "Mediator M",
    "guide.mediator_placeholder": "Mediator M",
    "guide.moderated_mediation": "Moderated mediation",
    "guide.moderated_model": "Moderated-mediation model",
    "guide.moderator_accessible": "Moderator W",
    "guide.moderator_placeholder": "Moderator W",
    "guide.order_disclaimer": "Candidate order follows the current deterministic sorting rule, not verified accuracy or priority.",
    "guide.prepare_candidate": "Review configuration",
    "guide.repeated_measures_anova": "Repeated-measures ANOVA",
    "guide.review_configuration_required": "Required configuration review",
    "guide.review_heightened": "Focused research-model review",
    "guide.review_standard": "Review variable roles directly",
    "guide.x_accessible": "Independent variable X",
    "guide.x_placeholder": "Independent variable X",
    "guide.y_accessible": "Outcome variable Y",
    "guide.y_placeholder": "Outcome variable Y",
    "pipeline.apply_anova_factorial": "Apply two-factor ANOVA",
    "pipeline.apply_logistic_regression": "Apply logistic regression",
    "pipeline.factorial_factor_a": "Factor A",
    "pipeline.factorial_factor_b": "Factor B",
    "pipeline.factorial_levels_a": "Factor A levels",
    "pipeline.factorial_levels_b": "Factor B levels",
    "pipeline.factorial_outcome": "Outcome variable",
    "pipeline.logistic_event": "Event value",
    "pipeline.logistic_event_accessible": "Logistic-regression event value",
    "pipeline.logistic_reference": "Reference category",
    "pipeline.logistic_reference_accessible": "Logistic-regression reference category",
    "research.candidate.claim": "Interpretation boundary",
    "research.candidate.evidence": "Validation evidence",
    "research.candidate.method": "Method to prepare",
    "research.candidate.passport": "Passport",
    "research.candidate.review_state": "Review status",
    "research.candidate.roles": "Variable roles",
    "research.abstention.details": "Decision basis",
    "research.failure.details": "Problem and next step",
    "research.close": "Close Research OS",
    "research.close_description": "Closes the local research-task guide.",
    "research.confirm": "Confirm this configuration",
    "research.confirm_description": "Confirms only the displayed setup.",
    "research.direct_available": "Direct analysis remains available at any time.",
    "research.direct_manual": "Open direct analysis settings",
    "research.legacy.collapse": "Collapse quick candidates",
    "research.legacy.expand": "View quick candidates based on data shape",
    "research.legacy.title": "Quick candidates based on data shape",
    "research.open": "Open Research OS",
    "research.open_description": "Opens the local research-task guide.",
    "research.panel.accessible": "Local Research OS task guide",
    "research.panel.title": "Research OS",
    "research.meaning.accessible": "Review current variable meanings and research roles",
    "research.meaning.boundary": "Confirm only the displayed metadata. Concept definitions and units that were not recorded are not inferred.",
    "research.meaning.definition_unit": "Concept definition · unit",
    "research.meaning.digest": "Meaning review ID",
    "research.meaning.dtype": "Storage type",
    "research.meaning.label": "Display label",
    "research.meaning.measure": "Measurement level",
    "research.meaning.measure.nominal": "Nominal",
    "research.meaning.measure.ordinal": "Ordinal",
    "research.meaning.measure.scale": "Scale",
    "research.meaning.missing_codes": "Missing codes",
    "research.meaning.none": "None",
    "research.meaning.not_recorded": "Not recorded",
    "research.meaning.role.after": "Later measurement",
    "research.meaning.role.before": "Earlier measurement",
    "research.meaning.role.focal_predictor": "Co-measured variable",
    "research.meaning.role.group": "Group variable",
    "research.meaning.role.outcome": "Outcome variable",
    "research.meaning.value_labels": "Value labels",
    "research.preparation.digest": "Configuration review ID",
    "research.preparation.confirmed_badge": "Setup confirmed",
    "research.preparation.review_badge": "Setup review",
    "research.preparation.settings": "Settings to review",
    "research.preparation.step": "Analysis step",
    "research.profile.category_frequency.body": "Summarize counts and proportions for one or more categorical variables. Do not interpret them causally.",
    "research.profile.category_frequency.title": "Category counts and proportions",
    "research.profile.independent_two_group_mean.body": "Compare a numeric mean across two nonoverlapping groups. Do not interpret the difference as a causal effect.",
    "research.profile.independent_two_group_mean.title": "Mean difference between two independent groups",
    "research.profile.linear_co_movement.body": "Summarize straight-line co-movement while preserving the spacing of two numeric variables. Do not interpret it causally.",
    "research.profile.linear_co_movement.title": "Linear co-movement between numeric variables",
    "research.profile.none": "None of these tasks applies",
    "research.profile.numeric_distribution.body": "Summarize the distribution of one or more numeric variables. Do not interpret it causally.",
    "research.profile.numeric_distribution.title": "Distribution of numeric variables",
    "research.profile.paired_two_time_mean_change.body": "Compare the mean change between before and after measurements from the same person or unit. Do not interpret the change as a causal effect.",
    "research.profile.paired_two_time_mean_change.title": "Change between two measurements from the same unit",
    "research.profile.rank_co_movement.body": "Use the ranks of two variables to summarize one-direction co-movement. Do not interpret it causally.",
    "research.profile.rank_co_movement.title": "Rank-based co-movement",
    "research.question.answer_required": "Select one answer.",
    "research.question.caution": "Interpretation limit",
    "research.question.remaining": "What remains to be confirmed",
    "research.question.selection": "Why this question comes first",
    "research.question.variables_accessible": "Relevant variable-key list",
    "research.question.variables_placeholder": "Comma-separated variable keys · Leave blank if none applies",
    "research.question.why": "Why we ask this question",
    "research.roles.after": "After-measurement variable key",
    "research.roles.before": "Before-measurement variable key",
    "research.roles.group": "Group variable key",
    "research.roles.instructions": "Enter variable keys from the data table. Use commas between multiple variables. Unconfirmed entries do not carry decision authority.",
    "research.roles.outcome": "Outcome or summary variable key",
    "research.roles.predictor": "Variable key to examine alongside the outcome",
    "research.roles.required": "Enter every variable role required for this task.",
    "research.transformation_first": "Complete required data preparation such as reverse coding, scale construction, and missing-value handling before starting a research task. If the data changes, current answers must be reviewed again.",
}
