from __future__ import annotations

UI_STRINGS_KO = {
    "app.title": "Modori",
    "dialog.import.cancel": "취소",
    "dialog.import.columns_count": "선택한 열",
    "dialog.import.columns_count_separator": ": ",
    "dialog.import.columns_count_total_separator": " / ",
    "dialog.import.columns_empty": "가져올 열을 하나 이상 선택해 주세요.",
    "dialog.import.columns_reset": "모든 열 포함",
    "dialog.import.columns_search": "열 검색",
    "dialog.import.columns_title": "가져올 열",
    "dialog.import.confirm": "가져오기",
    "dialog.import.data_start_row": "데이터 시작 행",
    "dialog.import.drop_aggregate_rows": "집계/합계 행 제외",
    "dialog.import.drop_duplicate_rows": "완전히 동일한 중복 행 제외",
    "dialog.import.header_row": "헤더 행",
    "dialog.import.header_rows": "헤더 행 수",
    "dialog.import.preserve_metadata": "값 레이블·결측 코드 그대로 가져오기",
    "dialog.import.preserve_metadata_detail": "지원되는 파일의 값 레이블과 결측 코드를 유지합니다.",
    "dialog.import.preview_accessible": "데이터 미리보기",
    "dialog.import.refresh_preview": "미리보기 갱신",
    "dialog.import.review_accessible": "가져오기 행 판정 검토",
    "dialog.import.review_title": "행 판정 검토",
    "dialog.import.sheet_name": "시트",
    "dialog.import.settings": "가져오기 설정",
    "dialog.import.settings_collapse": "설정 접기",
    "dialog.import.title": "데이터 가져오기",
    "dialog.report.description": "현재 분석 결과를 Word(.docx)로 내보냅니다.",
    "dialog.report.export_word": "Word로 저장",
    "dialog.report.include_association": "빈도/상관 포함",
    "dialog.report.include_comparison": "집단비교 포함",
    "dialog.report.include_figures": "그림 포함",
    "dialog.report.include_descriptives": "기술통계 포함",
    "dialog.report.include_dimension_reduction": "요인/PCA 포함",
    "dialog.report.include_group_models": "분산분석/ANCOVA 포함",
    "dialog.report.include_regression": "회귀분석 포함",
    "dialog.report.include_reliability": "신뢰도 포함",
    "dialog.report.language": "보고서 언어",
    "dialog.report.language.en": "영어",
    "dialog.report.language.ko": "한국어",
    "dialog.report.sections": "포함할 내용",
    "dialog.report.title": "보고서 내보내기",
    "data.grid_columns": "열",
    "data.grid_empty": "표시할 데이터가 없습니다.",
    "data.grid_extent_separator": " · ",
    "data.grid_rows": "행",
    "data.edit_policy": "셀 직접 수정은 재현 가능한 편집 단계가 준비된 뒤 활성화됩니다.",
    "entry.guided": "안내 분석(실험적)",
    "entry.guided_description": "검증 중인 분석 후보를 살펴보고 구성을 직접 확인합니다.",
    "entry.promise": "데이터를 이 컴퓨터 안에서 분석하고, 선택 근거를 함께 확인합니다.",
    "entry.standard": "직접 분석",
    "entry.standard_description": "분석 방법과 변수 역할을 직접 정합니다.",
    "entry.open_data": "데이터 열기",
    "entry.footer": "무료 · 오픈소스 · 로컬",
    "entry.recent": "최근 항목",
    "explain.close": "닫기",
    "explain.close_accessible": "설명 닫기",
    "explain.title": "설명",
    "guide.ancova": "공변량 보정 집단 비교",
    "guide.anova_oneway": "세 집단 이상 평균 차이",
    "guide.comparison": "두 집단 평균 차이",
    "guide.correlation": "상관관계",
    "guide.covariates_accessible": "공변량",
    "guide.covariates_placeholder": "공변량: age, pretest",
    "guide.confirm_review": "연구 질문·변수 역할·표본 구조를 확인했습니다.",
    "guide.default_recommendation": "현재 검토 후보",
    "guide.descriptives": "기술통계 표",
    "guide.frequency_crosstab": "빈도/교차표",
    "guide.factor_pca": "요인/PCA",
    "guide.group_accessible": "집단 변수",
    "guide.group_placeholder": "집단 변수",
    "guide.dependent_placeholder": "종속 변수",
    "guide.items_accessible": "신뢰도 문항 변수",
    "guide.items_placeholder": "문항 변수: q1, q2, q3",
    "guide.experimental_badge": "실험적 후보",
    "guide.experimental_status": "검증 중인 분석 후보 · 자동 실행 안 함",
    "guide.manual_selection": "직접 선택",
    "guide.no_recommendation": "검토할 분석 후보 없음",
    "guide.other_recommendations": "다른 실험적 후보 보기",
    "guide.outcome_accessible": "결과 변수",
    "guide.outcome_placeholder": "결과 변수",
    "guide.predictors_accessible": "예측 변수",
    "guide.predictors_placeholder": "예측 변수: x1, x2",
    "guide.prepare_review": "구성 검토로 이동",
    "guide.question": "무엇을 알고 싶으세요?",
    "guide.reason": "이유",
    "guide.regression": "여러 변수로 예측",
    "guide.reliability": "척도 신뢰도",
    "guide.kruskal_wallis": "순위 기반 세 집단 비교",
    "guide.run_manual": "선택한 분석 실행",
    "guide.run_reviewed": "설정 확인 후 실행",
    "guide.review_required": "구성을 확인한 뒤 실행할 수 있습니다.",
    "guide.review_state": "검토 상태",
    "guide.title": "분석 후보 안내",
    "guide.variables_accessible": "분석 변수",
    "guide.variables_placeholder": "변수: q1, q2, q3",
    "loading.calculating": "계산 중",
    "pipeline.apply_ancova": "ANCOVA 적용",
    "pipeline.apply_anova_oneway": "ANOVA 적용",
    "pipeline.apply_comparison": "비교 적용",
    "pipeline.apply_correlation": "상관 적용",
    "pipeline.apply_descriptives": "기술통계 적용",
    "pipeline.apply_frequency_crosstab": "빈도 적용",
    "pipeline.apply_factor_pca": "요인/PCA 적용",
    "pipeline.apply_kruskal_wallis": "K-W 적용",
    "pipeline.apply_regression": "회귀 적용",
    "pipeline.apply_reliability": "신뢰도 적용",
    "pipeline.analysis_type": "분석 방법",
    "pipeline.covariates_accessible": "공변량",
    "pipeline.covariates_placeholder": "공변량",
    "pipeline.dependent_accessible": "표준 회귀 종속 변수",
    "pipeline.dependent_placeholder": "종속",
    "pipeline.group_accessible": "표준 집단 변수",
    "pipeline.group_placeholder": "집단",
    "pipeline.items_accessible": "표준 신뢰도 문항",
    "pipeline.items_placeholder": "q1, q2, q3",
    "pipeline.outcome_accessible": "표준 결과 변수",
    "pipeline.outcome_placeholder": "결과",
    "pipeline.predictors_accessible": "표준 회귀 예측 변수",
    "pipeline.predictors_placeholder": "x1, x2",
    "pipeline.run": "실행",
    "pipeline.rerun": "다시 실행",
    "pipeline.variables_accessible": "분석 변수",
    "pipeline.variables_placeholder": "변수",
    "privacy.local": "데이터는 이 컴퓨터를 떠나지 않습니다",
    "results.error_prefix": "오류: ",
    "results.empty": "대기",
    "results.empty_message": "분석을 실행하면 결과가 여기에 표시됩니다.",
    "results.figure": "그림",
    "results.latest": "최신",
    "results.notes": "주의",
    "results.path": "파일 위치",
    "results.report_preview": "결과 요약",
    "results.running": "계산 중",
    "results.stale": "이전 결과",
    "results.table": "결과 표",
    "results.title": "결과",
    "results.detail_title": "결과 표",
    "results.view_wide": "표 넓게 보기",
    "results.why_this_test": "이 분석을 선택한 이유",
    "settings.close": "닫기",
    "settings.description": "화면 표시와 최근 항목 저장 방식을 정합니다.",
    "settings.explain": "설명",
    "settings.explain_detail": "분석 선택 이유와 통계 용어 설명을 표시합니다.",
    "settings.recent_files": "최근 항목 저장",
    "settings.recent_files_detail": "끄면 이 컴퓨터에 저장된 최근 항목 목록도 삭제됩니다.",
    "settings.reduce_effects": "시각 효과 줄이기",
    "settings.reduce_effects_detail": "반사광과 움직임을 줄이고 정보 구조는 유지합니다.",
    "settings.title": "설정",
    "splash.subtitle": "통계 엔진을 준비하고 있어요",
    "transform.apply_reverse": "역코딩 변수 만들기",
    "transform.apply_scale": "척도 점수 변수 만들기",
    "transform.map_apply": "값 정리 단계 추가",
    "transform.map_column": "변수",
    "transform.map_missing": "결측으로 바꿀 값",
    "transform.map_missing_placeholder": "예: 무응답, 모름",
    "transform.map_new_value": "새 값",
    "transform.map_preview_missing": "건 결측 처리",
    "transform.map_preview_to": "건 → ",
    "transform.map_rules": "수정 규칙",
    "transform.map_rules_placeholder": "예: 남 자=남자",
    "transform.map_summary_rows": "개 행 수정 예정",
    "transform.map_summary_rows_with_text": "개 행 수정 + 자유 입력 규칙",
    "transform.map_summary_text": "자유 입력 규칙 적용 예정",
    "transform.map_suffix": "새 변수 접미사",
    "transform.map_suffix_default": "_수정",
    "transform.map_title": "값 수정",
    "transform.map_to_missing": "결측",
    "transform.map_values": "현재 값",
    "transform.method_mean": "평균",
    "transform.method_sum": "합계",
    "transform.min_valid": "유효 응답 비율",
    "transform.policy_conservative": "완전 응답만",
    "transform.policy_custom": "사용자 지정",
    "transform.policy_survey": "설문 기본",
    "transform.reverse_columns": "역코딩할 변수",
    "transform.reverse_columns_placeholder": "예: q3, q7",
    "transform.reverse_suffix": "새 변수 접미사",
    "transform.reverse_suffix_placeholder": "_R",
    "transform.reverse_title": "역코딩",
    "transform.scale_items": "문항 변수",
    "transform.scale_items_placeholder": "예: q1, q2, q3",
    "transform.scale_max": "최댓값",
    "transform.scale_method": "계산 방법",
    "transform.scale_min": "최솟값",
    "transform.scale_name": "새 변수 이름",
    "transform.scale_name_placeholder": "예: job_sat",
    "transform.scale_policy": "결측 처리",
    "transform.scale_title": "척도 점수 만들기",
    "transform.source_protected": "원본 데이터는 직접 수정하지 않습니다. 변환은 새 단계와 새 변수로 기록됩니다.",
    "transform.unify_apply": "표기 통일 단계 추가",
    "transform.unify_title": "표기 통일 제안",
    "variable.key_accessible": "변수 키",
    "variable.key_placeholder": "변수 키",
    "variable.label_placeholder": "변수 레이블",
    "variable.measure_accessible": "측정수준",
    "variable.measure_edit": "측정수준 변경",
    "variable.measure_nominal": "범주형",
    "variable.measure_ordinal": "순서형",
    "variable.measure_scale": "연속형",
    "variable.metadata_apply": "속성 변경",
    "variable.missing_codes_placeholder": "결측 코드: 9, 99",
    "work.analysis": "분석 다시 실행",
    "work.analysis_run": "분석 실행",
    "work.data": "데이터 열기",
    "work.data_menu": "데이터 메뉴",
    "work.data_sheet_window": "데이터 넓게 보기",
    "work.data_view": "데이터",
    "work.guided": "안내 분석(실험적)",
    "work.report": "보고서",
    "work.report_menu": "보고서 메뉴",
    "work.standard": "직접 분석",
    "work.transform_view": "변환",
    "work.variable_view": "변수",
}
