from __future__ import annotations

from types import MappingProxyType


UI_STRINGS_KO = {
    "app.title": "Modori",
    "boundary.reconfirmation_required": "데이터 구성이 바뀌었습니다. 후보 구성을 다시 확인하거나 분석 방법을 직접 적용해 주세요.",
    "dialog.import.cancel": "취소",
    "dialog.import.columns_count": "선택한 열",
    "dialog.import.columns_count_separator": ": ",
    "dialog.import.columns_count_total_separator": " / ",
    "dialog.import.columns_empty": "가져올 열을 하나 이상 선택해 주세요.",
    "dialog.import.columns_reset": "모든 열 포함",
    "dialog.import.columns_search": "열 검색",
    "dialog.import.columns_title": "가져올 열",
    "dialog.import.confirm": "가져오기",
    "dialog.import.data_start_row": "데이터 시작 행",
    "dialog.import.drop_aggregate_rows": "집계/합계 행 제외",
    "dialog.import.drop_duplicate_rows": "완전히 동일한 중복 행 제외",
    "dialog.import.header_row": "헤더 행",
    "dialog.import.header_rows": "헤더 행 수",
    "dialog.import.preserve_metadata": "값 레이블·결측 코드 그대로 가져오기",
    "dialog.import.preserve_metadata_detail": "지원되는 파일의 값 레이블과 결측 코드를 유지합니다.",
    "dialog.import.preview_accessible": "데이터 미리보기",
    "dialog.import.refresh_preview": "미리보기 갱신",
    "dialog.import.review_accessible": "가져오기 행 판정 검토",
    "dialog.import.review_title": "행 판정 검토",
    "dialog.import.sheet_recovery": (
        "기본 시트에서 표를 찾지 못했습니다. 표가 있는 시트를 선택하고 "
        "미리보기를 새로 고치세요."
    ),
    "dialog.import.sheet_name": "시트",
    "dialog.import.settings": "가져오기 설정",
    "dialog.import.settings_collapse": "설정 접기",
    "dialog.import.title": "데이터 가져오기",
    "dialog.report.description": "현재 분석 결과를 Word(.docx)로 내보냅니다.",
    "dialog.report.conflict_body": "기존 파일을 바꾸면 이전 내용은 사라집니다.",
    "dialog.report.conflict_title": "같은 이름의 보고서가 있습니다",
    "dialog.report.export_word": "Word로 저장",
    "dialog.report.include_association": "빈도/상관 포함",
    "dialog.report.include_comparison": "집단비교 포함",
    "dialog.report.include_figures": "그림 포함",
    "dialog.report.include_descriptives": "기술통계 포함",
    "dialog.report.include_dimension_reduction": "요인/PCA 포함",
    "dialog.report.include_group_models": "분산분석/ANCOVA 포함",
    "dialog.report.include_regression": "회귀분석 포함",
    "dialog.report.include_reliability": "신뢰도 포함",
    "dialog.report.language": "보고서 언어",
    "dialog.report.language.en": "영어",
    "dialog.report.language.ko": "한국어",
    "dialog.report.keep_existing": "기존 파일 유지",
    "dialog.report.replace_existing": "기존 파일 바꾸기",
    "dialog.report.sections": "포함할 내용",
    "dialog.report.title": "보고서 내보내기",
    "data.grid_accessible": "데이터 표",
    "data.grid_columns": "열",
    "data.grid_empty": "표시할 데이터가 없습니다.",
    "data.grid_extent_separator": " · ",
    "data.grid_keyboard_help": (
        "화살표 키로 이동합니다. Ctrl+Shift+F는 현재 열 맞춤, "
        "Ctrl+Shift+R은 모든 열 너비 초기화입니다."
    ),
    "data.grid_rows": "행",
    "data.edit_policy": "셀 직접 수정은 재현 가능한 편집 단계가 준비된 뒤 활성화됩니다.",
    "entry.guided": "GUIDED MODE",
    "entry.guided_description": (
        "연구 질문과 데이터 구조를 따라 분석 후보와 필요한 확인을 단계별로 안내합니다.\n"
        "실험적 연구 가이드 · 설정과 실행은 직접 확인"
    ),
    "entry.heading": "시작하기",
    "entry.language": "언어",
    "entry.promise": "통계 작업을 위한 선택,\n모도리에 오신 것을 환영합니다.",
    "entry.selected": "선택됨",
    "entry.standard": "PRO MODE",
    "entry.standard_description": "분석 방법과 변수 역할을 직접 정합니다.",
    "entry.open_data": "데이터 열기",
    "entry.footer": "무료 · 오픈소스 · 로컬",
    "entry.recent": "최근 항목",
    "explain.close": "닫기",
    "explain.close_accessible": "설명 닫기",
    "explain.title": "설명",
    "guide.ancova": "공변량 보정 집단 비교",
    "guide.anova_oneway": "세 집단 이상 평균 차이",
    "guide.anova_factorial": "두 요인의 평균 차이와 상호작용",
    "guide.comparison": "두 집단 평균 차이",
    "guide.correlation": "상관관계",
    "guide.covariates_accessible": "공변량",
    "guide.covariates_placeholder": "공변량: age, pretest",
    "guide.confirm_review": "연구 질문·변수 역할·표본 구조를 확인했습니다.",
    "guide.default_recommendation": "현재 검토 후보",
    "guide.descriptives": "기술통계 표",
    "guide.frequency_crosstab": "빈도/교차표",
    "guide.factor_pca": "요인/PCA",
    "guide.group_accessible": "집단 변수",
    "guide.group_placeholder": "집단 변수",
    "guide.dependent_placeholder": "종속 변수",
    "guide.items_accessible": "신뢰도 문항 변수",
    "guide.items_placeholder": "문항 변수: q1, q2, q3",
    "guide.experimental_status": "실험적 가이드",
    "guide.explanation_unavailable": "설명 근거를 불러올 수 없습니다.",
    "guide.form_unavailable": "이 후보는 아직 안내 화면에서 구성할 수 없습니다. 직접 선택에서 지원되는 분석을 선택해 주세요.",
    "guide.manual_selection": "직접 선택",
    "guide.no_recommendation": "현재 규칙으로 표시할 분석 후보가 없습니다. 수동 분석을 사용할 수 있습니다.",
    "guide.other_recommendations": "다른 후보 보기",
    "guide.outcome_accessible": "결과 변수",
    "guide.outcome_placeholder": "결과 변수",
    "guide.predictors_accessible": "예측 변수",
    "guide.predictors_placeholder": "예측 변수: x1, x2",
    "guide.prepare_review": "구성 검토로 이동",
    "guide.reason": "이유",
    "guide.regression": "여러 변수로 예측",
    "guide.reliability": "척도 신뢰도",
    "guide.kruskal_wallis": "순위 기반 세 집단 비교",
    "guide.run_manual": "이 설정으로 계산 실행",
    "guide.run_reviewed": "설정 확인 후 실행",
    "guide.review_required": "변수와 구성을 확인하고 동의한 뒤 실행할 수 있습니다.",
    "guide.review_state": "검토 상태",
    "guide.title": "분석 후보 안내",
    "guide.logistic_regression": "두 결과 중 하나와 관련된 요인",
    "guide.logistic_event": "사건(event)으로 해석할 결과값",
    "guide.logistic_event_accessible": "로지스틱 회귀 사건값",
    "guide.logistic_reference": "기준범주",
    "guide.logistic_reference_accessible": "로지스틱 회귀 기준범주",
    "guide.factorial_outcome": "결과 변수",
    "guide.factorial_factor_a": "요인 A",
    "guide.factorial_factor_b": "요인 B",
    "guide.factorial_levels_a": "요인 A 수준",
    "guide.factorial_levels_b": "요인 B 수준",
    "guide.order_disclaimer": "후보 순서는 검증된 정확도나 우선순위가 아니라 현재의 결정론적 정렬 규칙입니다.",
    "guide.candidate_list": "분석 후보 목록",
    "guide.candidate_label": "분석 후보",
    "guide.review_standard": "변수 역할 직접 확인",
    "guide.review_configuration_required": "필수 설정 확인 필요",
    "guide.review_heightened": "연구모형 집중 검토 필요",
    "guide.prepare_candidate": "설정 검토",
    "guide.confirm_candidate": "연구 질문, 변수 역할, 표본 구조를 확인했습니다.",
    "guide.repeated_measures_anova": "반복측정 분산분석",
    "guide.friedman": "반복측정 순위 분석",
    "guide.mediation": "매개분석",
    "guide.moderated_mediation": "조절된 매개분석",
    "guide.measures_accessible": "반복측정 변수",
    "guide.measures_placeholder": "반복측정 변수: time1, time2, time3",
    "guide.x_accessible": "독립 변수 X",
    "guide.x_placeholder": "독립 변수 X",
    "guide.mediator_accessible": "매개 변수 M",
    "guide.mediator_placeholder": "매개 변수 M",
    "guide.moderator_accessible": "조절 변수 W",
    "guide.moderator_placeholder": "조절 변수 W",
    "guide.y_accessible": "결과 변수 Y",
    "guide.y_placeholder": "결과 변수 Y",
    "guide.moderated_model": "조절된 매개 모형",
    "guide.variables_accessible": "분석 변수",
    "guide.variables_placeholder": "변수: q1, q2, q3",
    "language.en": "English",
    "language.ko": "한국어",
    "loading.calculating": "로딩 중",
    "pipeline.apply_ancova": "ANCOVA 적용",
    "pipeline.apply_anova_oneway": "ANOVA 적용",
    "pipeline.apply_anova_factorial": "이원 ANOVA 적용",
    "pipeline.apply_comparison": "비교 적용",
    "pipeline.apply_correlation": "상관 적용",
    "pipeline.apply_descriptives": "기술통계 적용",
    "pipeline.apply_frequency_crosstab": "빈도 적용",
    "pipeline.apply_factor_pca": "요인/PCA 적용",
    "pipeline.apply_kruskal_wallis": "K-W 적용",
    "pipeline.apply_logistic_regression": "로지스틱 적용",
    "pipeline.apply_regression": "회귀 적용",
    "pipeline.apply_reliability": "신뢰도 적용",
    "pipeline.analysis_type": "분석 방법",
    "pipeline.covariates_accessible": "공변량",
    "pipeline.covariates_placeholder": "공변량",
    "pipeline.dependent_accessible": "표준 회귀 종속 변수",
    "pipeline.dependent_placeholder": "종속",
    "pipeline.group_accessible": "표준 집단 변수",
    "pipeline.group_placeholder": "집단",
    "pipeline.items_accessible": "표준 신뢰도 문항",
    "pipeline.items_placeholder": "q1, q2, q3",
    "pipeline.logistic_event": "사건값",
    "pipeline.logistic_event_accessible": "로지스틱 회귀 사건값",
    "pipeline.logistic_reference": "기준범주",
    "pipeline.logistic_reference_accessible": "로지스틱 회귀 기준범주",
    "pipeline.factorial_outcome": "결과 변수",
    "pipeline.factorial_factor_a": "요인 A",
    "pipeline.factorial_factor_b": "요인 B",
    "pipeline.factorial_levels_a": "요인 A 수준",
    "pipeline.factorial_levels_b": "요인 B 수준",
    "pipeline.outcome_accessible": "표준 결과 변수",
    "pipeline.outcome_placeholder": "결과",
    "pipeline.predictors_accessible": "표준 회귀 예측 변수",
    "pipeline.predictors_placeholder": "x1, x2",
    "pipeline.run": "실행",
    "pipeline.rerun": "다시 실행",
    "pipeline.variables_accessible": "분석 변수",
    "pipeline.variables_placeholder": "변수",
    "privacy.local": "데이터는 이 컴퓨터를 떠나지 않습니다",
    "results.error_prefix": "오류: ",
    "results.empty": "대기",
    "results.empty_message": "분석을 실행하면 결과가 여기에 표시됩니다.",
    "results.figure": "그림",
    "results.latest": "최신",
    "results.notes": "주의",
    "results.path": "파일 위치",
    "results.report_preview": "결과 요약",
    "results.running": "계산 중",
    "results.stale": "이전 결과",
    "results.table": "결과 표",
    "results.title": "결과",
    "results.detail_title": "결과 표",
    "results.view_wide": "표 넓게 보기",
    "results.explain_cronbach_alpha": "Cronbach 알파 설명",
    "research.candidate.claim": "해석 경계",
    "research.candidate.evidence": "검사 근거",
    "research.candidate.method": "준비할 방법",
    "research.candidate.passport": "패스포트",
    "research.candidate.review_state": "검토 상태",
    "research.candidate.roles": "변수 역할",
    "research.abstention.details": "결정 근거",
    "research.failure.details": "문제와 다음 단계",
    "research.close": "Research OS 닫기",
    "research.close_description": "로컬 연구과업 안내를 닫습니다.",
    "research.confirm": "이 설정 확인",
    "research.confirm_description": "표시된 설정만 확인합니다.",
    "research.direct_available": "직접 분석은 언제든 사용할 수 있습니다.",
    "research.direct_manual": "직접 분석 설정 열기",
    "research.legacy.collapse": "빠른 후보 접기",
    "research.legacy.expand": "데이터 모양 기반 빠른 후보 보기",
    "research.legacy.title": "데이터 모양 기반 빠른 후보",
    "research.open": "Research OS 열기",
    "research.open_description": "로컬 연구과업 안내를 엽니다.",
    "research.panel.accessible": "로컬 Research OS 연구과업 안내",
    "research.panel.title": "Research OS",
    "research.meaning.accessible": "현재 데이터의 변수 의미와 연구 역할 검토",
    "research.meaning.boundary": "표시된 메타데이터만 확인합니다. 기록되지 않은 개념 정의나 단위는 추정하지 않습니다.",
    "research.meaning.definition_unit": "개념 정의 · 단위",
    "research.meaning.digest": "의미 검토 번호",
    "research.meaning.dtype": "저장 자료형",
    "research.meaning.label": "표시 이름",
    "research.meaning.measure": "측정수준",
    "research.meaning.measure.nominal": "명목형",
    "research.meaning.measure.ordinal": "순서형",
    "research.meaning.measure.scale": "척도형",
    "research.meaning.missing_codes": "결측 코드",
    "research.meaning.none": "없음",
    "research.meaning.not_recorded": "기록되지 않음",
    "research.meaning.role.after": "이후 측정",
    "research.meaning.role.before": "이전 측정",
    "research.meaning.role.focal_predictor": "함께 살펴볼 변수",
    "research.meaning.role.group": "집단 변수",
    "research.meaning.role.outcome": "결과 변수",
    "research.meaning.value_labels": "값 라벨",
    "research.preparation.digest": "설정 검토 번호",
    "research.preparation.confirmed_badge": "설정 확인됨",
    "research.preparation.review_badge": "설정 검토",
    "research.preparation.settings": "확인할 설정",
    "research.preparation.step": "분석 단계",
    "research.profile.category_frequency.body": "하나 이상의 범주형 변수에서 빈도와 비율을 요약합니다. 인과관계로 해석하지 않습니다.",
    "research.profile.category_frequency.title": "범주별 빈도와 비율",
    "research.profile.independent_two_group_mean.body": "서로 겹치지 않는 두 집단의 수치 평균을 비교합니다. 차이를 인과효과로 해석하지 않습니다.",
    "research.profile.independent_two_group_mean.title": "두 독립 집단의 평균 차이",
    "research.profile.linear_co_movement.body": "두 수치 변수의 간격을 보존한 직선형 동반 변화를 요약합니다. 인과관계로 해석하지 않습니다.",
    "research.profile.linear_co_movement.title": "수치 간 직선형 동반 변화",
    "research.profile.none": "이 과업들에 해당하지 않음",
    "research.profile.numeric_distribution.body": "하나 이상의 수치 변수에서 분포를 요약합니다. 인과관계로 해석하지 않습니다.",
    "research.profile.numeric_distribution.title": "수치 변수의 분포",
    "research.profile.paired_two_time_mean_change.body": "같은 사람이나 단위에서 이전과 이후 측정의 평균 변화를 비교합니다. 변화를 인과효과로 해석하지 않습니다.",
    "research.profile.paired_two_time_mean_change.title": "같은 단위의 두 측정 변화",
    "research.profile.rank_co_movement.body": "두 변수의 순위를 사용해 한 방향의 동반 변화를 요약합니다. 인과관계로 해석하지 않습니다.",
    "research.profile.rank_co_movement.title": "순위에 따른 동반 변화",
    "research.question.answer_required": "답변 하나를 선택해 주세요.",
    "research.question.caution": "설명의 한계",
    "research.question.remaining": "아직 남은 확인",
    "research.question.selection": "이 질문이 먼저인 이유",
    "research.question.variables_accessible": "해당 변수 키 목록",
    "research.question.variables_placeholder": "변수 키를 쉼표로 구분 · 해당 없음이면 비워 둠",
    "research.question.why": "이 질문을 드리는 이유",
    "research.roles.after": "이후 측정 변수 키",
    "research.roles.before": "이전 측정 변수 키",
    "research.roles.group": "집단 변수 키",
    "research.roles.instructions": "데이터 표의 변수 키를 입력합니다. 쉼표는 여러 변수를 구분하며, 아직 확인 전인 입력은 권한 있는 결정이 아닙니다.",
    "research.roles.outcome": "결과 또는 요약 변수 키",
    "research.roles.predictor": "함께 살펴볼 변수 키",
    "research.roles.required": "현재 과업에 필요한 변수 역할을 모두 입력해 주세요.",
    "research.transformation_first": "역코딩·척도 구성·결측 처리처럼 분석 전에 필요한 데이터 변환을 먼저 마친 뒤 연구과업을 시작하세요. 데이터가 바뀌면 현재 답변은 다시 확인해야 합니다.",
    "settings.close": "닫기",
    "settings.description": "화면 표시와 최근 항목 저장 방식을 정합니다.",
    "settings.explain": "설명",
    "settings.explain_detail": "지원되는 결과의 통계 용어 설명을 표시합니다.",
    "settings.recent_files": "최근 항목 저장",
    "settings.recent_files_detail": "끄면 이 컴퓨터에 저장된 최근 항목 목록도 삭제됩니다.",
    "settings.reduce_effects": "시각 효과 줄이기",
    "settings.reduce_effects_detail": "반사광과 움직임을 줄이고 정보 구조는 유지합니다.",
    "settings.title": "설정",
    "splash.subtitle": "통계 엔진을 준비하고 있어요",
    "transform.apply_reverse": "역코딩 변수 만들기",
    "transform.apply_scale": "척도 점수 변수 만들기",
    "transform.map_apply": "값 정리 단계 추가",
    "transform.map_column": "변수",
    "transform.map_missing": "결측으로 바꿀 값",
    "transform.map_missing_placeholder": "예: 무응답, 모름",
    "transform.map_new_value": "새 값",
    "transform.map_preview_missing": "건 결측 처리",
    "transform.map_preview_to": "건 → ",
    "transform.map_rules": "수정 규칙",
    "transform.map_rules_placeholder": "예: 남 자=남자",
    "transform.map_summary_rows": "개 행 수정 예정",
    "transform.map_summary_rows_with_text": "개 행 수정 + 자유 입력 규칙",
    "transform.map_summary_text": "자유 입력 규칙 적용 예정",
    "transform.map_suffix": "새 변수 접미사",
    "transform.map_suffix_default": "_수정",
    "transform.map_title": "값 수정",
    "transform.map_to_missing": "결측",
    "transform.map_values": "현재 값",
    "transform.method_mean": "평균",
    "transform.method_sum": "합계",
    "transform.min_valid": "유효 응답 비율",
    "transform.policy_conservative": "완전 응답만",
    "transform.policy_custom": "사용자 지정",
    "transform.policy_survey": "설문 기본",
    "transform.reverse_columns": "역코딩할 변수",
    "transform.reverse_columns_placeholder": "예: q3, q7",
    "transform.reverse_suffix": "새 변수 접미사",
    "transform.reverse_suffix_placeholder": "_R",
    "transform.reverse_title": "역코딩",
    "transform.scale_items": "문항 변수",
    "transform.scale_items_placeholder": "예: q1, q2, q3",
    "transform.scale_max": "최댓값",
    "transform.scale_method": "계산 방법",
    "transform.scale_min": "최솟값",
    "transform.scale_name": "새 변수 이름",
    "transform.scale_name_placeholder": "예: job_sat",
    "transform.scale_policy": "결측 처리",
    "transform.scale_title": "척도 점수 만들기",
    "transform.source_protected": "원본 데이터는 직접 수정하지 않습니다. 변환은 새 단계와 새 변수로 기록됩니다.",
    "transform.unify_apply": "표기 통일 단계 추가",
    "transform.unify_title": "표기 통일 제안",
    "variable.key_accessible": "변수 키",
    "variable.key_placeholder": "변수 키",
    "variable.label_placeholder": "변수 레이블",
    "variable.measure_accessible": "측정수준",
    "variable.measure_edit": "측정수준 변경",
    "variable.measure_nominal": "범주형",
    "variable.measure_ordinal": "순서형",
    "variable.measure_scale": "연속형",
    "variable.metadata_apply": "속성 변경",
    "variable.missing_codes_placeholder": "결측 코드: 9, 99",
    "work.analysis": "분석 다시 실행",
    "work.analysis_run": "분석 실행",
    "work.reconfirmation_required": "구성 재확인 필요",
    "work.data": "데이터 열기",
    "work.data_menu": "데이터 메뉴",
    "work.data_sheet_window": "데이터 시트 열기",
    "work.data_view": "데이터",
    "work.guided": "GUIDED MODE",
    "work.report": "보고서",
    "work.report_menu": "보고서 메뉴",
    "work.standard": "PRO MODE",
    "work.transform_view": "변환",
    "work.variable_view": "변수",
}


_RESEARCH_FLOW_KO = {
    "action.answer": "답변 기록",
    "action.answer_not_sure": "잘 모르겠습니다",
    "action.back": "돌아가기",
    "action.cancel": "중단",
    "action.causal_no": "아니요, 인과 해석이 아닙니다",
    "action.causal_not_sure": "잘 모르겠습니다",
    "action.causal_record": "이 제한을 기록하고 계속",
    "action.causal_yes": "예, 인과 해석을 원합니다",
    "action.prepare": "구성 검토로 이동",
    "action.reframe_noncausal": "인과 효과 대신 변수 간 관계 확인",
    "action.replan": "현재 데이터로 다시 계획",
    "action.retract": "이 결정 철회",
    "action.resume": "기록에서 다시 확인",
    "action.retry_current_data": "현재 데이터 다시 확인",
    "action.retry_local_record": "로컬 기록 다시 열기",
    "action.resume_verified": "마지막 확인 상태로 돌아가기",
    "action.leave_unsafe_record": "안전한 시작 화면으로 돌아가기",
    "action.select_profile": "연구과업 선택",
    "action.start": "연구과업 시작",
    "action.submit_roles": "변수 역할 확인",
    "action.confirm_meanings": "변수 의미와 역할 확인",
    "badge.abstain": "기권 기록",
    "badge.abstain_causal": "인과 요청 기권",
    "badge.cancelled": "중단됨",
    "badge.clarify": "확인 필요",
    "badge.error": "작업 실패",
    "badge.integrity": "무결성 확인 필요",
    "badge.local": "로컬 Research OS",
    "badge.pending": "복구 대기",
    "badge.retracted": "철회됨",
    "badge.scope": "범위 안내",
    "badge.stale": "재계획 필요",
    "badge.unavailable": "로컬 기능 사용 불가",
    "busy.committing": "연구과업 기록을 준비하는 중",
    "busy.fingerprinting": "데이터 버전을 확인하는 중",
    "busy.handoff_preflight": "분석 설정이 현재 데이터에서 가능한지 확인하는 중",
    "busy.meaning_reviewing": "현재 데이터의 변수 의미와 역할을 묶어 확인하는 중",
    "candidate.blocked_review_status": "현재 데이터에서는 구성을 준비할 수 없음",
    "candidate.blocked_badge": "설정 준비 안 됨",
    "candidate.blocked_boundary": "현재 데이터에서는 이 후보의 설정을 준비할 수 없습니다.",
    "candidate.prepare_boundary": "다음 단계에서 변수 역할과 설정을 검토합니다.",
    "candidate.ready_badge": "후보 준비됨",
    "candidate.review_status": "검토 필요",
    "abstention.reason.causal": "요청이 인과 효과 해석을 요구하지만 현재 Research OS는 비인과 과업만 지원합니다.",
    "abstention.reason.clarification": "현재 확인 정보와 질문 한도에서는 지원 가능한 후보를 결정할 수 없습니다.",
    "abstention.reason.integrity": "현재 기록 또는 데이터 결합의 무결성을 확인할 수 없습니다.",
    "abstention.reason.unsupported": "현재 지원 범위에서 안정된 분석 후보를 확정할 수 없습니다.",
    "abstention.reason_code": "기권 사유 코드",
    "abstention.reason_label": "기권 이유",
    "abstention.recovery_requirement": "복구 요구 ID",
    "abstention.additional_reason_codes": "추가 사유 코드 수",
    "abstention.additional_recovery_requirements": "추가 복구 요구 수",
    "capability.category_frequency": "범주별 빈도와 비율 요약",
    "capability.independent_two_group_mean": "서로 겹치지 않는 두 집단의 평균 차이",
    "capability.linear_co_movement": "수치 간 직선형 동반 변화",
    "capability.numeric_distribution": "수치 변수의 분포 요약",
    "capability.paired_two_time_mean_change": "같은 단위에서 두 시점의 평균 변화",
    "capability.rank_co_movement": "순위에 따른 단조 동반 변화",
    "claim.association": "변수 간 연관성만 요약하며 인과관계로 해석하지 않습니다.",
    "claim.frequency": "이 표본에 기록된 범주별 빈도와 비율만 요약합니다.",
    "claim.group_mean": "관측된 두 집단의 평균 차이이며 인과효과로 해석하지 않습니다.",
    "claim.paired_mean": "같은 단위에서 관측된 평균 변화이며 인과효과로 해석하지 않습니다.",
    "claim.summary": "이 표본에 기록된 값의 분포만 요약합니다.",
    "evidence.blocked_condition": "준비를 막은 조건",
    "evidence.capability": "연구과업",
    "evidence.claim_boundary": "해석 경계",
    "evidence.method": "방법 식별자",
    "evidence.passport": "패스포트",
    "evidence.preflight": "실행 전 구조 검사",
    "evidence.preflight_blocked": "구성 준비 불가",
    "evidence.preflight_ready": "구성 검토 가능",
    "failure.reason_label": "확인된 원인",
    "failure.next_step_label": "다음 단계",
    "failure.reason_id": "원인 ID",
    "failure.reason.current_data_context_unavailable": "현재 데이터나 가져오기 구성을 Research OS가 안전하게 읽지 못했습니다.",
    "failure.reason.dataset_fingerprint_unavailable": "현재 데이터의 로컬 식별을 제한 시간 안에 완료하지 못했습니다.",
    "failure.reason.local_record_unavailable": "연구과업의 로컬 기록 파일을 지금 열 수 없습니다.",
    "failure.reason.local_record_conflict": "로컬 연구과업 기록이 다른 작업에서 바뀌었거나 현재 사용 중입니다.",
    "failure.reason.local_record_changed": "마지막 확인 뒤 데이터 또는 연구과업 기록이 바뀌었습니다.",
    "failure.reason.local_record_integrity_failed": "로컬 원장 또는 봉인된 연구과업 기록의 무결성을 확인하지 못했습니다.",
    "failure.reason.request_verification_failed": "현재 선택과 기록을 하나의 안전한 연구과업 요청으로 확인하지 못했습니다.",
    "failure.reason.preflight_unsupported_step": "기록된 분석 단계가 현재 실행 전 검사 범위에 포함되지 않습니다.",
    "failure.reason.preflight_invalid_configuration": "봉인된 분석 설정을 현재 스키마로 다시 확인하지 못했습니다.",
    "failure.reason.preflight_verification_failed": "현재 데이터에서 실행 전 구조 검사를 완료하지 못했습니다.",
    "failure.reason.preparation_review_failed": "확인할 분석 설정 화면을 마지막 검증 상태에서 만들지 못했습니다.",
    "failure.reason.worker_operation_failed": "백그라운드 Research OS 작업이 완료되기 전에 중단되었습니다.",
    "failure.recovery.current_data_context_unavailable": "데이터 시트와 가져오기 단계를 확인한 뒤 현재 데이터를 다시 확인하세요.",
    "failure.recovery.dataset_fingerprint_unavailable": "잠시 후 현재 데이터 확인을 다시 시도하세요. 계산 엔진은 실행되지 않았습니다.",
    "failure.recovery.local_record_unavailable": "로컬 기록을 다시 열어 마지막 확인 상태를 복구하세요.",
    "failure.recovery.local_record_conflict": "로컬 기록을 다시 열어 최신 확인 상태를 읽은 뒤 계속하세요.",
    "failure.recovery.local_record_changed": "현재 데이터에서 새 연구과업으로 명시적으로 다시 계획하세요.",
    "failure.recovery.local_record_integrity_failed": "이 연구과업 기록은 사용하지 말고 안전한 시작 화면으로 돌아가 직접 분석을 사용하세요.",
    "failure.recovery.request_verification_failed": "마지막으로 확인된 기록으로 돌아가 선택 내용을 다시 검토하세요.",
    "failure.recovery.preflight_unsupported_step": "현재 데이터에서 새 연구과업으로 다시 계획하고 지원되는 분석 단계를 선택하세요.",
    "failure.recovery.preflight_invalid_configuration": "현재 데이터에서 새 연구과업으로 다시 계획해 설정을 새로 확인하세요.",
    "failure.recovery.preflight_verification_failed": "현재 데이터에서 새 연구과업으로 다시 계획한 뒤 구조 검사를 다시 실행하세요.",
    "failure.recovery.preparation_review_failed": "마지막으로 확인된 후보를 다시 불러와 설정 검토를 다시 시작하세요.",
    "failure.recovery.worker_operation_failed": "마지막으로 확인된 기록을 다시 불러오세요. 완료되지 않은 작업은 자동 적용되지 않습니다.",
    "issue.boolean_not_allowed": "연속형 역할에 불리언 값이 포함됨",
    "issue.dataset_empty": "현재 데이터에 행이 없음",
    "issue.duplicate_display_label": "서로 다른 역할의 표시 이름이 같음",
    "issue.duplicate_variable": "같은 변수가 중복 선택됨",
    "issue.group_too_small": "집단별 완전 관측치가 현재 엔진 최소치보다 적음",
    "issue.insufficient_categories": "관측된 범주 수가 부족함",
    "issue.invalid_params": "봉인된 분석 설정을 현재 스키마로 확인할 수 없음",
    "issue.missing_variable": "선택된 변수가 현재 데이터에 없음",
    "issue.no_nonmissing_value": "선택된 변수에 유효한 관측값이 없음",
    "issue.non_finite": "무한대 또는 유한하지 않은 수치가 포함됨",
    "issue.non_numeric": "연속형 역할의 저장값이 숫자로 사용할 수 없음",
    "issue.p1_group_requires_categorical": "집단 역할이 범주형으로 확인되지 않음",
    "issue.p1_requires_scale": "연속형 역할이 척도형으로 확인되지 않음",
    "issue.pearson_requires_scale": "Pearson 설정에는 두 척도형 변수가 필요함",
    "issue.pipeline_changed": "검사 중 데이터 또는 분석 단계 버전이 바뀜",
    "issue.preflight_failure": "실행 전 구조 검사를 완료하지 못함",
    "issue.role_collision": "서로 달라야 할 변수 역할이 겹침",
    "issue.too_few_complete_pairs": "완전한 관측 쌍이 현재 엔진 최소치보다 적음",
    "issue.unsupported_measure": "현재 분석이 지원하지 않는 측정수준임",
    "issue.unsupported_step_type": "봉인된 분석 단계 유형을 지원하지 않음",
    "issue.wrong_group_cardinality": "관측된 집단 수가 정확히 둘이 아님",
    "issue.zero_paired_difference_variance": "쌍을 이룬 차이값의 분산이 0임",
    "issue.zero_variance": "필요한 변수 또는 집단의 분산이 0임",
    "method.descriptive_table": "기술통계 표",
    "method.frequency_table": "빈도표",
    "method.paired_t": "대응표본 t 방법",
    "method.pearson": "Pearson 곱률상관",
    "method.spearman": "Spearman 순위상관",
    "method.welch": "Welch 두 독립표본 t 방법",
    "option.not_sure": "잘 모르겠습니다",
    "role.after": "이후 측정",
    "role.before": "이전 측정",
    "role.focal_predictor": "함께 살펴볼 변수",
    "role.group": "집단 변수",
    "role.outcome": "결과 변수",
    "role.variable": "요약 변수",
    "state.abstain_ready.body": "현재 확인된 사실과 지원 범위에서는 분석 후보를 내지 않기로 기록했습니다. 직접 분석은 계속 사용할 수 있습니다.",
    "state.abstain_ready.title": "지원 범위에서 후보를 확정하지 않았습니다",
    "state.abstain_causal.body": "요청이 인과 효과 해석을 요구해 후보를 내지 않았습니다. 비인과 관계로 바꾸려면 아래에서 명시적으로 선택하세요. 인과 의도를 유지하면 이 기권은 그대로 남습니다.",
    "state.abstain_causal.title": "인과 효과 요청은 현재 지원 범위 밖입니다",
    "state.cancelled.body": "요청한 작업을 중단했습니다. 마지막으로 확인된 기록은 그대로 보존됩니다.",
    "state.cancelled.title": "작업을 중단했습니다",
    "state.candidate_ready.body": "봉인된 연구과업과 현재 데이터의 구조 검사를 바탕으로 정확한 설정을 검토할 수 있습니다.",
    "state.candidate_ready.title": "분석 설정 후보를 검토합니다",
    "state.clarify_ready.body": "분석 방법을 좁히기 전에 연구 사실 한 가지를 확인합니다.",
    "state.clarify_ready.title": "다음 확인 항목",
    "state.committing.body": "선택한 내용을 로컬 원장에 기록하고 다시 확인합니다.",
    "state.committing.title": "연구과업 기록을 준비하고 있습니다",
    "state.confirmed.body": "설정 확인이 기록되었습니다. 계산은 별도의 실행 명령에서만 시작됩니다.",
    "state.confirmed.title": "설정 확인 완료",
    "state.corruption.body": "로컬 원장 또는 봉인된 기록의 무결성을 확인할 수 없습니다. 해당 연구과업 기록은 사용하지 않습니다. 직접 분석은 계속 사용할 수 있습니다.",
    "state.corruption.title": "연구과업 기록의 무결성을 확인할 수 없습니다",
    "state.failure.body": "요청한 Research OS 작업이 실패했습니다. 이 상태만으로 원장 손상을 뜻하지 않으며 직접 분석은 계속 사용할 수 있습니다.",
    "state.failure.title": "Research OS 작업을 완료하지 못했습니다",
    "state.fingerprinting.body": "현재 데이터와 변수 구성을 같은 연구과업에 다시 연결할 수 있도록 로컬에서 식별하고 있습니다.",
    "state.fingerprinting.title": "현재 데이터 버전을 확인하고 있습니다",
    "state.handoff_preflight.body": "봉인된 방법과 변수 역할이 현재 계산 단계에서 구성 가능한지 구조만 확인합니다.",
    "state.handoff_preflight.title": "분석 설정을 확인하고 있습니다",
    "state.idle.body": "변환을 마친 뒤 제한된 연구과업 안내를 시작할 수 있습니다. 직접 분석은 언제든 사용할 수 있습니다.",
    "state.idle.title": "Research OS를 시작할 수 있습니다",
    "state.intake_blocked.body": "인과 해석 여부가 확인되지 않아 연구과업 추천을 시작하지 않습니다.",
    "state.intake_blocked.title": "먼저 연구 해석 범위를 확인해야 합니다",
    "state.intake_causal.body": "결과를 원인과 결과의 관계로 해석하려는 연구인지 선택해 주세요.",
    "state.intake_causal.title": "인과 해석을 원하십니까?",
    "state.intake_profile.body": "현재 검증 범위에 포함된 여섯 가지 연구과업 중 하나를 선택합니다.",
    "state.intake_profile.title": "무엇을 알아보려는지 선택해 주세요",
    "state.intake_roles.body": "방법 이름이 아니라 연구에서 각 변수가 맡는 역할을 확인합니다.",
    "state.intake_roles.title": "변수 역할을 확인합니다",
    "state.meaning_reviewing.body": "현재 데이터 메타데이터와 선택한 역할을 로컬에서 묶고 있습니다. 아직 원장에는 기록하지 않습니다.",
    "state.meaning_reviewing.title": "변수 의미 검토를 준비하고 있습니다",
    "state.variable_meaning_review.body": "변수 이름, 표시 이름, 측정수준, 값 라벨과 결측 코드를 확인하세요. 개념 정의와 단위가 기록되지 않은 항목은 추정하지 않습니다.",
    "state.variable_meaning_review.title": "변수 의미와 역할을 확인합니다",
    "state.manual_run.body": "명시적인 실행 요청에서만 계산이 시작됩니다.",
    "state.manual_run.title": "계산 실행 단계",
    "state.memory_unavailable.body": "필요한 로컬 기록 경로를 현재 사용할 수 없습니다. 분석 데이터는 외부로 전송되지 않았으며 직접 분석은 계속 사용할 수 있습니다.",
    "state.memory_unavailable.title": "로컬 연구과업 기록을 사용할 수 없습니다",
    "state.preparation_blocked.body": "현재 데이터에서는 봉인된 정확한 설정을 준비할 수 없습니다. 분석은 실행되지 않았습니다.",
    "state.preparation_blocked.title": "현재 데이터에서 구성을 준비할 수 없습니다",
    "state.prepare_review.body": "봉인된 방법, 변수 역할, 해석 경계를 실행 전에 확인합니다.",
    "state.prepare_review.title": "분석 설정 검토",
    "state.recovery_pending.body": "요청 기록은 남아 있지만 다음 패스포트가 완전히 커밋되지 않았습니다. 자동으로 다시 시도하지 않습니다.",
    "state.recovery_pending.title": "연구과업 기록 복구가 필요합니다",
    "state.replan_required.body": "이전 결정은 현재 데이터와 더 이상 결합되지 않습니다. 현재 데이터로 새 연구과업을 시작해야 합니다.",
    "state.replan_required.title": "현재 데이터로 다시 계획해야 합니다",
    "state.retracted.body": "이 패스포트는 철회되어 질문이나 분석 후보의 권한으로 다시 사용할 수 없습니다.",
    "state.retracted.title": "이전 결정을 철회했습니다",
    "state.static_causal.body": "P1은 인과효과 해석을 지원하지 않습니다. 이 제한만 먼저 확인할 수 있으며, 기록을 선택하기 전에는 원장을 만들지 않습니다.",
    "state.static_causal.title": "현재 범위는 비인과 연구과업입니다",
    "state.static_causal_unknown.body": "인과 해석 여부가 모호하면 연구과업 추천을 시작하지 않습니다. 돌아가서 연구 의도를 확인해 주세요.",
    "state.static_causal_unknown.title": "인과 해석 여부가 필요합니다",
    "state.static_scope.body": "P1은 현재 여섯 가지 제한된 연구과업만 지원하며 검증된 외부 경로는 아직 없습니다. 직접 분석은 계속 사용할 수 있습니다.",
    "state.static_scope.title": "현재 Research OS 범위 밖입니다",
}


_RESEARCH_FLOW_EN = {
    "action.answer": "Record answer",
    "action.answer_not_sure": "Not sure",
    "action.back": "Go back",
    "action.cancel": "Cancel",
    "action.causal_no": "No, this is not a causal interpretation",
    "action.causal_not_sure": "Not sure",
    "action.causal_record": "Record this limit and continue",
    "action.causal_yes": "Yes, I want a causal interpretation",
    "action.prepare": "Review configuration",
    "action.reframe_noncausal": "Explore a relationship instead of a causal effect",
    "action.replan": "Replan with current data",
    "action.retract": "Retract this decision",
    "action.resume": "Recheck the local record",
    "action.retry_current_data": "Check the current data again",
    "action.retry_local_record": "Reopen the local record",
    "action.resume_verified": "Return to the last verified state",
    "action.leave_unsafe_record": "Return to the safe start screen",
    "action.select_profile": "Select research task",
    "action.start": "Start research task",
    "action.submit_roles": "Confirm variable roles",
    "action.confirm_meanings": "Confirm meanings and roles",
    "badge.abstain": "Recorded abstention",
    "badge.abstain_causal": "Causal request abstained",
    "badge.cancelled": "Cancelled",
    "badge.clarify": "Clarification needed",
    "badge.error": "Operation failed",
    "badge.integrity": "Integrity review required",
    "badge.local": "Local Research OS",
    "badge.pending": "Recovery pending",
    "badge.retracted": "Retracted",
    "badge.scope": "Scope notice",
    "badge.stale": "Replan required",
    "badge.unavailable": "Local function unavailable",
    "busy.committing": "Preparing the local research-task record",
    "busy.fingerprinting": "Checking the data version",
    "busy.handoff_preflight": "Checking whether the analysis settings can be configured for the current data",
    "busy.meaning_reviewing": "Binding current variable metadata to the selected roles",
    "candidate.blocked_review_status": "Configuration cannot be prepared from the current data",
    "candidate.blocked_badge": "Setup not ready",
    "candidate.blocked_boundary": "This candidate's setup cannot be prepared from the current data.",
    "candidate.prepare_boundary": "Next, review variable roles and settings.",
    "candidate.ready_badge": "Candidate ready",
    "candidate.review_status": "Review required",
    "abstention.reason.causal": "The request requires a causal-effect interpretation, but the current Research OS supports only non-causal tasks.",
    "abstention.reason.clarification": "The confirmed information and question budget cannot determine a supported candidate.",
    "abstention.reason.integrity": "The current record or data binding could not be verified.",
    "abstention.reason.unsupported": "No stable analysis candidate can be issued within the current supported scope.",
    "abstention.reason_code": "Abstention reason code",
    "abstention.reason_label": "Why no candidate was issued",
    "abstention.recovery_requirement": "Recovery requirement ID",
    "abstention.additional_reason_codes": "Additional reason codes",
    "abstention.additional_recovery_requirements": "Additional recovery requirements",
    "capability.category_frequency": "Category counts and proportions",
    "capability.independent_two_group_mean": "Mean difference between two non-overlapping groups",
    "capability.linear_co_movement": "Straight-line co-movement between numeric variables",
    "capability.numeric_distribution": "Numeric-variable distribution summary",
    "capability.paired_two_time_mean_change": "Mean change between two measurements of the same unit",
    "capability.rank_co_movement": "Monotonic co-movement by ranks",
    "claim.association": "Summarizes association only; do not interpret it as causation.",
    "claim.frequency": "Summarizes only category counts and proportions recorded in this sample.",
    "claim.group_mean": "Describes the observed mean difference between two groups; do not interpret it as a causal effect.",
    "claim.paired_mean": "Describes the observed mean change within the same units; do not interpret it as a causal effect.",
    "claim.summary": "Describes only the distribution recorded in this sample.",
    "evidence.blocked_condition": "Blocked condition",
    "evidence.capability": "Research task",
    "evidence.claim_boundary": "Interpretation boundary",
    "evidence.method": "Method identity",
    "evidence.passport": "Passport",
    "evidence.preflight": "Structural preflight",
    "evidence.preflight_blocked": "Configuration blocked",
    "evidence.preflight_ready": "Ready for configuration review",
    "failure.reason_label": "What was confirmed",
    "failure.next_step_label": "Next step",
    "failure.reason_id": "Reason ID",
    "failure.reason.current_data_context_unavailable": "Research OS could not safely read the current data or import configuration.",
    "failure.reason.dataset_fingerprint_unavailable": "The local identity check for the current data did not finish within its time limit.",
    "failure.reason.local_record_unavailable": "The local record for this research task cannot be opened right now.",
    "failure.reason.local_record_conflict": "The local research-task record changed in another operation or is currently in use.",
    "failure.reason.local_record_changed": "The data or research-task record changed after the last verification.",
    "failure.reason.local_record_integrity_failed": "The integrity of the local ledger or sealed research-task record could not be verified.",
    "failure.reason.request_verification_failed": "The current choices and record could not be verified as one safe research-task request.",
    "failure.reason.preflight_unsupported_step": "The recorded analysis step is outside the current execution-preflight boundary.",
    "failure.reason.preflight_invalid_configuration": "The sealed analysis configuration could not be verified against the current schema.",
    "failure.reason.preflight_verification_failed": "The execution-preflight structure check did not finish for the current data.",
    "failure.reason.preparation_review_failed": "The reviewable analysis setup could not be built from the last verified state.",
    "failure.reason.worker_operation_failed": "The background Research OS operation stopped before it completed.",
    "failure.recovery.current_data_context_unavailable": "Check the data sheet and import step, then check the current data again.",
    "failure.recovery.dataset_fingerprint_unavailable": "Try the current-data check again shortly. The calculation engine was not started.",
    "failure.recovery.local_record_unavailable": "Reopen the local record to recover the last verified state.",
    "failure.recovery.local_record_conflict": "Reopen the local record to read the latest verified state before continuing.",
    "failure.recovery.local_record_changed": "Explicitly start a fresh research task from the current data.",
    "failure.recovery.local_record_integrity_failed": "Do not use this research-task record. Return to the safe start screen and use direct analysis.",
    "failure.recovery.request_verification_failed": "Return to the last verified record and review the current choices.",
    "failure.recovery.preflight_unsupported_step": "Replan from the current data and choose a supported analysis step.",
    "failure.recovery.preflight_invalid_configuration": "Replan from the current data and review a fresh configuration.",
    "failure.recovery.preflight_verification_failed": "Replan from the current data, then run the structure check again.",
    "failure.recovery.preparation_review_failed": "Reload the last verified candidate and start setup review again.",
    "failure.recovery.worker_operation_failed": "Reload the last verified record. The incomplete operation was not applied automatically.",
    "issue.boolean_not_allowed": "Boolean values appear in a continuous-variable role",
    "issue.dataset_empty": "The current dataset has no rows",
    "issue.duplicate_display_label": "Distinct roles have the same display label",
    "issue.duplicate_variable": "The same variable was selected more than once",
    "issue.group_too_small": "Complete observations per group are below the current engine minimum",
    "issue.insufficient_categories": "Too few categories are observed",
    "issue.invalid_params": "The sealed settings do not validate under the current schema",
    "issue.missing_variable": "A selected variable is absent from the current data",
    "issue.no_nonmissing_value": "A selected variable has no usable observations",
    "issue.non_finite": "Infinite or non-finite numeric values are present",
    "issue.non_numeric": "Stored values in a continuous role cannot be used as numbers",
    "issue.p1_group_requires_categorical": "The group role is not confirmed as categorical",
    "issue.p1_requires_scale": "A continuous role is not confirmed as scale",
    "issue.pearson_requires_scale": "The Pearson setting requires two scale variables",
    "issue.pipeline_changed": "The data or pipeline version changed during the check",
    "issue.preflight_failure": "The structural preflight could not be completed",
    "issue.role_collision": "Variable roles that must differ overlap",
    "issue.too_few_complete_pairs": "Complete pairs are below the current engine minimum",
    "issue.unsupported_measure": "The current analysis does not support this measurement level",
    "issue.unsupported_step_type": "The sealed analysis-step type is unsupported",
    "issue.wrong_group_cardinality": "The observed number of groups is not exactly two",
    "issue.zero_paired_difference_variance": "Variance of the paired differences is zero",
    "issue.zero_variance": "A required variable or group has zero variance",
    "method.descriptive_table": "Descriptive table",
    "method.frequency_table": "Frequency table",
    "method.paired_t": "Paired-samples t method",
    "method.pearson": "Pearson product-moment correlation",
    "method.spearman": "Spearman rank correlation",
    "method.welch": "Welch two-independent-samples t method",
    "option.not_sure": "Not sure",
    "role.after": "Later measurement",
    "role.before": "Earlier measurement",
    "role.focal_predictor": "Co-measured variable",
    "role.group": "Group variable",
    "role.outcome": "Outcome variable",
    "role.variable": "Summary variable",
    "state.abstain_ready.body": "The recorded facts and supported scope do not permit an analysis candidate. Direct analysis remains available.",
    "state.abstain_ready.title": "No candidate was issued within the supported scope",
    "state.abstain_causal.body": "No candidate was issued because the request requires a causal-effect interpretation. Explicitly choose the non-causal reframe below, or keep this abstention if causal intent remains.",
    "state.abstain_causal.title": "The causal-effect request is outside the current scope",
    "state.cancelled.body": "The requested operation was cancelled. The last verified local record remains unchanged.",
    "state.cancelled.title": "Operation cancelled",
    "state.candidate_ready.body": "The sealed research task and structural preflight permit review of the exact settings.",
    "state.candidate_ready.title": "Review the analysis-settings candidate",
    "state.clarify_ready.body": "One research fact must be confirmed before narrowing the analysis method.",
    "state.clarify_ready.title": "Next clarification",
    "state.committing.body": "The selected information is being recorded and rechecked in the local ledger.",
    "state.committing.title": "Preparing the research-task record",
    "state.confirmed.body": "The settings were confirmed. Calculation starts only from a separate Run command.",
    "state.confirmed.title": "Settings confirmed",
    "state.corruption.body": "The integrity of the local ledger or sealed record cannot be verified. That research-task record will not be used. Direct analysis remains available.",
    "state.corruption.title": "Research-task record integrity cannot be verified",
    "state.failure.body": "The requested Research OS operation failed. This state alone does not imply ledger corruption, and direct analysis remains available.",
    "state.failure.title": "Research OS operation failed",
    "state.fingerprinting.body": "The current data and variable structure are being identified locally so later decisions can bind to the same version.",
    "state.fingerprinting.title": "Checking the current data version",
    "state.handoff_preflight.body": "Only the structural feasibility of the sealed method and variable roles is being checked.",
    "state.handoff_preflight.title": "Checking analysis settings",
    "state.idle.body": "After transformations are complete, you can start the limited research-task guide. Direct analysis remains available at any time.",
    "state.idle.title": "Research OS is ready to start",
    "state.intake_blocked.body": "The research-task guide will not start until causal interpretation is resolved.",
    "state.intake_blocked.title": "The interpretation boundary must be confirmed first",
    "state.intake_causal.body": "Choose whether the study is intended to interpret a cause-and-effect relationship.",
    "state.intake_causal.title": "Do you want a causal interpretation?",
    "state.intake_profile.body": "Select one of the six research tasks in the current verified scope.",
    "state.intake_profile.title": "What do you want to learn?",
    "state.intake_roles.body": "Confirm what each variable represents in the study rather than selecting a method name.",
    "state.intake_roles.title": "Confirm variable roles",
    "state.meaning_reviewing.body": "Current dataset metadata and the selected roles are being bound locally. Nothing has been written to the ledger yet.",
    "state.meaning_reviewing.title": "Preparing the variable-meaning review",
    "state.variable_meaning_review.body": "Check variable IDs, labels, measurement levels, value labels, and missing codes. Concept definitions and units that were not recorded are not inferred.",
    "state.variable_meaning_review.title": "Confirm variable meanings and roles",
    "state.manual_run.body": "Calculation starts only after an explicit Run request.",
    "state.manual_run.title": "Calculation run stage",
    "state.memory_unavailable.body": "The required local record path is currently unavailable. No analysis data was sent elsewhere, and direct analysis remains available.",
    "state.memory_unavailable.title": "Local research-task memory is unavailable",
    "state.preparation_blocked.body": "The exact sealed settings cannot be prepared from the current data. No analysis was run.",
    "state.preparation_blocked.title": "Configuration cannot be prepared from the current data",
    "state.prepare_review.body": "Review the sealed method, variable roles, and interpretation boundary before execution.",
    "state.prepare_review.title": "Review analysis settings",
    "state.recovery_pending.body": "A request record exists, but the next passport was not fully committed. Modori will not retry automatically.",
    "state.recovery_pending.title": "Research-task record recovery is pending",
    "state.replan_required.body": "The prior decision no longer binds the current data. Start a fresh research task for the current data.",
    "state.replan_required.title": "Replanning is required for the current data",
    "state.retracted.body": "This passport was retracted and cannot regain authority as a question or analysis candidate.",
    "state.retracted.title": "Prior decision retracted",
    "state.static_causal.body": "P1 does not support causal-effect interpretation. You can review this limit before recording anything; no ledger is created until you choose to record it.",
    "state.static_causal.title": "The current scope is noncausal",
    "state.static_causal_unknown.body": "When causal intent is unclear, the research-task guide does not start. Go back and confirm the intended interpretation.",
    "state.static_causal_unknown.title": "Causal intent is required",
    "state.static_scope.body": "P1 currently supports only six limited research tasks and has no verified external route. Direct analysis remains available.",
    "state.static_scope.title": "Outside the current Research OS scope",
}


RESEARCH_FLOW_STRINGS = MappingProxyType(
    {
        "ko": MappingProxyType(_RESEARCH_FLOW_KO),
        "en": MappingProxyType(_RESEARCH_FLOW_EN),
    }
)
