from __future__ import annotations

UI_STRINGS_KO = {
    "app.title": "Modori",
    "app.subtitle": "모도리",
    "dialog.import.cancel": "취소",
    "dialog.import.confirm": "가져오기",
    "dialog.import.preserve_metadata": "값 레이블·결측 코드 그대로 가져오기",
    "dialog.import.preview_accessible": "데이터 미리보기",
    "dialog.import.title": "데이터 가져오기",
    "dialog.report.description": "현재 분석 결과를 Word(.docx)로 내보냅니다.",
    "dialog.report.export_word": "Word 내보내기",
    "dialog.report.include_comparison": "집단비교 포함",
    "dialog.report.include_figures": "그림 포함",
    "dialog.report.include_regression": "회귀분석 포함",
    "dialog.report.include_reliability": "신뢰도 포함",
    "dialog.report.language.en": "English",
    "dialog.report.language.ko": "한국어",
    "dialog.report.title": "보고서 내보내기",
    "data.edit_policy": "셀 직접 수정은 재현 가능한 편집 단계가 준비된 뒤 활성화됩니다.",
    "entry.guided": "안내 모드",
    "entry.standard": "표준 모드",
    "entry.open_data": "데이터 열기",
    "entry.footer": "무료 · 오픈소스 · 로컬",
    "entry.recent": "최근 항목",
    "explain.close": "닫기",
    "explain.close_accessible": "설명 닫기",
    "explain.title": "설명",
    "guide.apply_selection": "선택 적용",
    "guide.comparison": "두 집단 평균 차이",
    "guide.default_recommendation": "기본 추천",
    "guide.group_accessible": "집단 변수",
    "guide.group_placeholder": "집단 변수",
    "guide.dependent_placeholder": "종속 변수",
    "guide.items_accessible": "신뢰도 문항 변수",
    "guide.items_placeholder": "문항 변수: q1, q2, q3",
    "guide.level": "수준",
    "guide.manual_selection": "직접 선택",
    "guide.no_recommendation": "추천 없음",
    "guide.other_recommendations": "다른 추천 보기",
    "guide.outcome_accessible": "결과 변수",
    "guide.outcome_placeholder": "결과 변수",
    "guide.predictors_accessible": "예측 변수",
    "guide.predictors_placeholder": "예측 변수: x1, x2",
    "guide.question": "무엇을 알고 싶으세요?",
    "guide.reason": "이유",
    "guide.regression": "여러 변수로 예측",
    "guide.reliability": "척도 신뢰도",
    "guide.run_recommended": "추천 분석 실행",
    "guide.run_manual": "선택한 분석 실행",
    "guide.title": "안내",
    "loading.calculating": "계산 중",
    "pipeline.apply_comparison": "비교 적용",
    "pipeline.apply_regression": "회귀 적용",
    "pipeline.apply_reliability": "신뢰도 적용",
    "pipeline.dependent_accessible": "표준 회귀 종속 변수",
    "pipeline.dependent_placeholder": "종속",
    "pipeline.group_accessible": "표준 집단 변수",
    "pipeline.group_placeholder": "집단",
    "pipeline.items_accessible": "표준 신뢰도 문항",
    "pipeline.items_placeholder": "q1, q2, q3",
    "pipeline.outcome_accessible": "표준 결과 변수",
    "pipeline.outcome_placeholder": "결과",
    "pipeline.predictors_accessible": "표준 회귀 예측 변수",
    "pipeline.predictors_placeholder": "x1, x2",
    "pipeline.rerun": "다시 실행",
    "privacy.local": "데이터는 이 컴퓨터를 떠나지 않습니다",
    "results.error_prefix": "오류: ",
    "results.empty": "대기",
    "results.empty_message": "분석을 실행하면 결과가 여기에 표시됩니다.",
    "results.figure": "그림",
    "results.latest": "최신",
    "results.notes": "주의",
    "results.path": "파일 위치",
    "results.report_preview": "보고서 미리보기",
    "results.running": "계산 중",
    "results.stale": "이전 결과",
    "results.table": "결과 표",
    "results.title": "결과",
    "results.why_this_test": "왜 이 검정?",
    "splash.subtitle": "통계 엔진을 준비하고 있어요",
    "transform.apply_reverse": "역코딩 적용",
    "transform.apply_scale": "척도 점수 적용",
    "transform.method_mean": "평균",
    "transform.method_sum": "합계",
    "transform.min_valid": "유효 응답 비율",
    "transform.policy_conservative": "완전 응답만",
    "transform.policy_custom": "사용자 지정",
    "transform.policy_survey": "설문 기본",
    "transform.reverse_columns": "역코딩할 변수",
    "transform.reverse_columns_placeholder": "예: q3, q7",
    "transform.reverse_suffix": "새 변수 접미사",
    "transform.reverse_suffix_placeholder": "_R",
    "transform.reverse_title": "역코딩",
    "transform.scale_items": "문항 변수",
    "transform.scale_items_placeholder": "예: q1, q2, q3",
    "transform.scale_max": "최댓값",
    "transform.scale_method": "계산 방법",
    "transform.scale_min": "최솟값",
    "transform.scale_name": "새 변수 이름",
    "transform.scale_name_placeholder": "예: job_sat",
    "transform.scale_policy": "결측 처리",
    "transform.scale_title": "척도 점수 만들기",
    "transform.source_protected": "원본 데이터는 직접 수정하지 않습니다. 변환은 새 단계와 새 변수로 기록됩니다.",
    "variable.key_accessible": "변수 키",
    "variable.key_placeholder": "변수 키",
    "variable.label_placeholder": "변수 레이블",
    "variable.measure_accessible": "측정수준",
    "variable.measure_edit": "측정수준 변경",
    "variable.metadata_apply": "속성 변경",
    "variable.missing_codes_placeholder": "결측 코드: 9, 99",
    "work.analysis": "분석",
    "work.analysis_run": "분석 실행",
    "work.data": "데이터",
    "work.data_menu": "데이터 메뉴",
    "work.data_view": "데이터 보기",
    "work.explain_mode": "설명 모드",
    "work.guided": "안내",
    "work.reduce_effects": "가벼운 모드",
    "work.report": "보고서",
    "work.report_menu": "보고서 메뉴",
    "work.standard": "표준",
    "work.transform_view": "변환",
    "work.variable_view": "변수 보기",
}
