import QtQuick

QtObject {
    readonly property color canvasCream: "#F4F0E8"
    readonly property color surfaceCream: "#FCFAF5"
    readonly property color surfaceRaised: "#EEE8DE"
    readonly property color surfaceQuiet: "#F7F3EB"
    readonly property color pearlMint: "#EFF4F0"
    readonly property color pearlRose: "#F6EFEC"
    readonly property color pearlLilac: "#F2F0F5"
    readonly property color focusRing: "#2B6F65"
    readonly property color semanticGlow: "#8CB8AF"
    readonly property color transparent: "transparent"

    readonly property color deepTeal: "#2E4D47"
    readonly property color brandTeal: "#376F67"
    readonly property color actionTeal: "#2C776B"
    readonly property color aqua: "#E2ECE7"
    readonly property color gold: "#B98B3E"
    readonly property color orange: "#B87743"
    readonly property color transformAccent: "#A96F78"
    readonly property color porcelainBackground: canvasCream
    readonly property color guideSurface: surfaceQuiet
    readonly property color subtleSurface: surfaceQuiet
    readonly property color quietSurface: surfaceRaised
    readonly property color popoverSurface: surfaceCream
    readonly property color paperSurface: surfaceCream
    readonly property color surface: surfaceCream
    readonly property color gridColumnHeaderSurface: "#E7EFE9"
    readonly property color gridRowHeaderSurface: "#F0E8DA"
    readonly property color gridHeaderText: "#27423B"
    readonly property color flatBackground: canvasCream
    readonly property color lineSubtle: "#DDD6CC"
    readonly property color lineStrong: "#C9C1B7"
    readonly property color lineGrid: "#D7DED8"
    readonly property color lineRail: "#D2C9BC"
    readonly property color lineDialog: "#CFC6BA"
    readonly property color linePopover: "#93B9AD"
    readonly property color textStrong: "#24332F"
    readonly property color textBody: "#485A54"
    readonly property color textControl: "#35463F"
    readonly property color textTable: "#1E2925"
    readonly property color textSecondary: "#5A6B65"
    readonly property color textLevel: "#48675F"
    readonly property color textMuted: "#6E7B76"
    readonly property color textSoft: "#89958F"
    readonly property color onBrand: "#FFFFFF"
    readonly property color onBrandDanger: "#FFE6E6"
    readonly property color selectionSurface: "#E3ECE7"
    readonly property color warning: "#8B641F"
    readonly property color warningSurface: "#F5E8C8"
    readonly property color danger: "#A33D4B"
    readonly property color dangerSurface: "#F5E2E3"
    readonly property color brandScrim: "#80243E38"

    readonly property int radiusSmall: 6
    readonly property int radiusMedium: 10
    readonly property int radiusLarge: 14
    readonly property int checkboxRadius: 4
    readonly property int borderWidth: 1
    readonly property int borderWidthFocus: 2

    readonly property int spaceXs: 4
    readonly property int spaceTight: 6
    readonly property int spaceSm: 8
    readonly property int spaceGridColumn: 10
    readonly property int spaceMd: 12
    readonly property int spaceHeaderGap: 10
    readonly property int spaceContent: 16
    readonly property int spaceLg: 18
    readonly property int spaceRailHorizontal: 20
    readonly property int spaceXl: 24
    readonly property int spaceNone: 0
    readonly property int spaceGridRow: 8

    readonly property int fontHero: 44
    readonly property int fontSplashTitle: 46
    readonly property int fontSplashSubtitle: 18
    readonly property int fontSubtitle: 20
    readonly property int fontOverlay: 22
    readonly property int fontTitle: 16
    readonly property int fontSection: 14
    readonly property int fontBody: 12
    readonly property int fontCaption: 11

    readonly property int windowDefaultWidth: 1180
    readonly property int windowDefaultHeight: 760
    readonly property int entryViewportMargin: 56
    readonly property int entryStartMaxWidth: 1000
    readonly property int entryStartMaxHeight: 580
    readonly property int entryBrandColumnWidth: 390
    readonly property int entryRecentMaxHeight: 132
    readonly property int entryCardPadding: 40
    readonly property int entryColumnGap: 36
    readonly property int workOuterMargin: 12
    readonly property int detachedSheetWidth: 980
    readonly property int detachedSheetHeight: 640
    readonly property int headerHeight: 56
    readonly property int commandSurfaceHeight: 52
    readonly property int pipelineHeight: 176
    readonly property int pipelineCompactHeight: 68
    readonly property int resultsPanelPreferredWidth: 420
    readonly property int guideRailPreferredWidth: 260
    readonly property int guideRailMinimumWidth: 220
    readonly property int guideRailMaximumWidth: 360
    readonly property int dialogViewportMargin: 48
    readonly property int importDialogMaxWidth: 760
    readonly property int importDialogMaxHeight: 620
    readonly property int importPreviewColumnWidth: 410
    readonly property int importPreviewColumnMinimumWidth: 320
    readonly property int importSettingsColumnMinimumWidth: 250
    readonly property int importReviewMaxHeight: 132
    readonly property int importColumnMinimumHeight: 96
    readonly property int importSettingsHeight: 264
    readonly property int importReviewRowNumberWidth: 24
    readonly property int importReviewRowSpacing: 1
    readonly property int popoverWidth: 420
    readonly property int popoverBodyHeight: 320
    readonly property int progressWidth: 280
    readonly property int tableCellWidth: 120
    readonly property int tableCellHeight: 32
    readonly property int gridHeaderHeight: 28
    readonly property int gridRowLabelWidth: 56
    readonly property int gridStatusHeight: 28
    readonly property int variableCellWidth: 140
    readonly property int variableCellHeight: 34
    readonly property int fieldWidthTiny: 80
    readonly property int fieldWidthSmall: 130
    readonly property int fieldWidthMedium: 180
    readonly property int badgeHeight: 22
    readonly property int badgeHorizontalPadding: 18
    readonly property int controlHeight: 34
    readonly property int iconButtonSize: 34
    readonly property int iconSize: 16
    readonly property int compactGlyphSize: 12
    readonly property int checkboxIndicatorSize: 18
    readonly property int radioDotSize: 8
    readonly property int spinIndicatorWidth: 28
    readonly property int switchTrackWidth: 38
    readonly property int switchTrackHeight: 20
    readonly property int switchThumbSize: 16
    readonly property int switchThumbInset: 2
    readonly property int preferenceMinimumWidth: 320
    readonly property int settingsDialogWidth: 520
    readonly property int resultDetailWidth: 820
    readonly property int resultDetailHeight: 560
    readonly property int reportDialogWidth: 560
    readonly property int reportDialogHeight: 520
    readonly property int tooltipDelayMs: 450
    readonly property int tablePreviewHeight: 206
    readonly property int chartPreviewHeight: 228
    readonly property int radiusPill: 999
    readonly property int splashFastDelayMs: 100
    readonly property int splashDelayMs: 800

    readonly property real opacityHigh: 0.9
    readonly property real opacityPrivacy: 0.86
    readonly property real opacitySplashPrivacy: 0.85
    readonly property real opacitySoft: 0.72
    readonly property real opacityDisabled: 0.46
    readonly property real stateBorderAlpha: 0.25
    readonly property real resultSummaryLineHeight: 1.18
}
