import QtQuick

QtObject {
    readonly property color deepTeal: "#0B4A43"
    readonly property color brandTeal: "#0F6E56"
    readonly property color actionTeal: "#0FA396"
    readonly property color aqua: "#DDF3EF"
    readonly property color gold: "#D9A441"
    readonly property color orange: "#D88A2D"
    readonly property color transformAccent: "#B76E79"
    readonly property color porcelainBackground: "#F4F7F6"
    readonly property color guideSurface: "#EFF7F3"
    readonly property color subtleSurface: "#FAFCFB"
    readonly property color quietSurface: "#EEF2F1"
    readonly property color popoverSurface: "#F8FBF9"
    readonly property color paperSurface: "#FFFFFF"
    readonly property color surface: "#FFFFFF"
    readonly property color gridColumnHeaderSurface: "#EDF5F2"
    readonly property color gridRowHeaderSurface: "#F6F0E5"
    readonly property color gridHeaderText: "#27423B"
    readonly property color flatBackground: "#F7FAF8"
    readonly property color lineSubtle: "#E3EAE8"
    readonly property color lineStrong: "#DCE4E1"
    readonly property color lineGrid: "#E4ECE8"
    readonly property color lineRail: "#D9E5DF"
    readonly property color lineDialog: "#D9E4DF"
    readonly property color linePopover: "#9FC7B9"
    readonly property color textStrong: "#22312E"
    readonly property color textBody: "#33463F"
    readonly property color textControl: "#26352F"
    readonly property color textTable: "#17211D"
    readonly property color textSecondary: "#486157"
    readonly property color textLevel: "#3A5F58"
    readonly property color textMuted: "#8A9993"
    readonly property color textSoft: "#9DB0AA"
    readonly property color onBrand: "#FFFFFF"
    readonly property color onBrandDanger: "#FFE6E6"
    readonly property color selectionSurface: "#E3F1EC"
    readonly property color warning: "#8A6A1F"
    readonly property color warningSurface: "#F8EBC9"
    readonly property color danger: "#B00020"
    readonly property color dangerSurface: "#FBE8EC"
    readonly property color brandScrim: "#800B4A43"

    readonly property int radiusSmall: 6
    readonly property int radiusMedium: 10
    readonly property int radiusLarge: 14

    readonly property int spaceXs: 4
    readonly property int spaceTight: 6
    readonly property int spaceSm: 8
    readonly property int spaceGridColumn: 10
    readonly property int spaceMd: 12
    readonly property int spaceHeaderGap: 14
    readonly property int spaceContent: 16
    readonly property int spaceLg: 18
    readonly property int spaceRailHorizontal: 20
    readonly property int spaceXl: 24
    readonly property int spaceNone: 0
    readonly property int spaceGridRow: 8

    readonly property int fontHero: 44
    readonly property int fontSplashTitle: 46
    readonly property int fontSplashSubtitle: 18
    readonly property int fontSubtitle: 20
    readonly property int fontOverlay: 22
    readonly property int fontTitle: 16
    readonly property int fontSection: 14
    readonly property int fontBody: 12
    readonly property int fontCaption: 11

    readonly property int windowDefaultWidth: 1180
    readonly property int windowDefaultHeight: 760
    readonly property int headerHeight: 56
    readonly property int pipelineHeight: 116
    readonly property int resultsPanelPreferredWidth: 360
    readonly property int guideRailPreferredWidth: 260
    readonly property int guideRailMinimumWidth: 220
    readonly property int guideRailMaximumWidth: 360
    readonly property int dialogViewportMargin: 48
    readonly property int importDialogMaxWidth: 760
    readonly property int importDialogMaxHeight: 620
    readonly property int importReviewMaxHeight: 132
    readonly property int importReviewRowNumberWidth: 24
    readonly property int importReviewRowSpacing: 1
    readonly property int popoverWidth: 420
    readonly property int popoverBodyHeight: 320
    readonly property int progressWidth: 280
    readonly property int tableCellWidth: 120
    readonly property int tableCellHeight: 32
    readonly property int gridHeaderHeight: 28
    readonly property int gridRowLabelWidth: 56
    readonly property int gridStatusHeight: 28
    readonly property int variableCellWidth: 140
    readonly property int variableCellHeight: 34
    readonly property int fieldWidthTiny: 80
    readonly property int fieldWidthSmall: 130
    readonly property int fieldWidthMedium: 180
    readonly property int badgeHeight: 22
    readonly property int badgeHorizontalPadding: 18
    readonly property int tablePreviewHeight: 206
    readonly property int chartPreviewHeight: 228
    readonly property int radiusPill: 999
    readonly property int splashFastDelayMs: 100
    readonly property int splashDelayMs: 800

    readonly property real opacityHigh: 0.9
    readonly property real opacityPrivacy: 0.86
    readonly property real opacitySplashPrivacy: 0.85
    readonly property real opacitySoft: 0.72
    readonly property real stateBorderAlpha: 0.25
    readonly property real resultSummaryLineHeight: 1.18
}
